### ISSUE TITLE
[Feature] opción de seleccionar un episodio inicial y uno final para descargar: 51 al 114 por ejemplo.

### ISSUE THREAD

**Issue by BattouKen** [Crunchy-DL/Crunchy-Downloader#101]
Opción de seleccionar un episodio inicial y uno final para descargarlos, ej: Ep. 51 al 114 por ejemplo. ya que seleccionar de a uno del 51 al 114 es una locura =(

![image](https://github.com/user-attachments/assets/1ab09e28-210b-44c5-9660-1ca231188e12)

**Comment by Vorffeed** [comment]
Para eso tienes esta opcion que te mete todo lo pendiente del tiron si tu ultimo marcado en verde es el 54 si tienes alguno superior desmarcalo y listo
![image](https://github.com/user-attachments/assets/ce40e13f-a351-455f-b030-5b9e11d0cda8)
