### ISSUE TITLE
[Bug] No puedo maximizar luego de haber dejar descargando.

### ISSUE THREAD

**Issue by BattouKen** [Crunchy-DL/Crunchy-Downloader#102]
No puedo maximizar luego de haber dejado descargando y minimizar la ventana y ya me sucede prácticamente siempre. tengo instalado .net Microsoft desktop runtime 8.0.4

https://github.com/user-attachments/assets/c6b090cd-7aa6-4fda-8830-300e4b2c5251

**Comment by BattouKen** [comment]
ok, click derecho y maximizar en el administrador de tareas funcionó. Pero sigue siendo un bug del programa que no se pueda recuperar la ventana haciéndole click ó alt+tab no?

![image](https://github.com/user-attachments/assets/7a2d4008-0b34-40f7-9bfc-bb5e3f001bc6)

**Comment by Elwador** [comment]
since i usually download minimized i wouldn't say this is a bug of the downloader - also i can't reproduce it

**Comment by BattouKen** [comment]
> since i usually download minimized i wouldn't say this is a bug of the downloader - also i can't reproduce it

bueno igual no pasa nada, supongo es un caso aislado referente a mi windows. Pero al menos puedo recuperar la ventana minimizada desde el administrador de tareas. 👍💯 ( ¿cierro el topic? )

**Comment by Vorffeed** [comment]
> > since i usually download minimized i wouldn't say this is a bug of the downloader - also i can't reproduce it
> 
> bueno igual no pasa nada, supongo es un caso aislado referente a mi windows. Pero al menos puedo recuperar la ventana minimizada desde el administrador de tareas. 👍💯 ( ¿cierro el topic? )

No es un caso aislado, lo acabo de probar y a mi me pasa igual como haya alguna descarga descargándose y minimices no vuelves a poder restaurar al ventana sino haces eso, para maximizar y poder ver si ya ha terminado todo el proceso😓

**Comment by Elwador** [comment]
ok i tried a few things and noticed one case where this happens 

1. it has nothing to do with downloading something
2. it only happens if you press the icon in the taskbar to minimize
3. if you minimize it with the button top right it works fine

i will release a fix later

**Comment by BattouKen** [comment]
> > > since i usually download minimized i wouldn't say this is a bug of the downloader - also i can't reproduce it
> > 
> > 
> > bueno igual no pasa nada, supongo es un caso aislado referente a mi windows. Pero al menos puedo recuperar la ventana minimizada desde el administrador de tareas. 👍💯 ( ¿cierro el topic? )
> 
> No es un caso aislado, lo acabo de probar y a mi me pasa igual como haya alguna descarga descargándose y minimices no vuelves a poder restaurar al ventana sino haces eso, para maximizar y poder ver si ya ha terminado todo el proceso😓

yo deje descargando 50 episodios, me los descargó sin dramas y eso que luego logre averiguar lo de maximizarla via adm. de tareas, o sea que realmente es un bug que solo hace eso, no deja maximizar la ventana desde la barra de tareas.

**Comment by BattouKen** [comment]
gracias, cuando necesite algo revisare si ya no me sucede 👍💯
