### ISSUE TITLE
[Bug] - Failed to download audio for a particular episode

### ISSUE THREAD

**Issue by ySergi** [Crunchy-DL/Crunchy-Downloader#103]
I'm trying to download Blue Lock, with Japanese and Spanish dubbing, but I'm getting an error while downloading. 
![image](https://github.com/user-attachments/assets/f0d97abd-b9d6-47c5-b67d-9e8b45891a0d)
Looking at the logfile, it says the following:
```
Part 350 download error:
	Error at segment 349: Response status code does not indicate success: 403 (Forbidden).
1 parts not downloaded
Faild to download audio - DL Stats: {"First":0,"Total":369,"Completed":340}
Part 350 download error:
	Error at segment 9: Response status code does not indicate success: 403 (Forbidden).
1 parts not downloaded
Faild to download audio - DL Stats: {"First":0,"Total":369,"Completed":340}
Part 350 download error:
	Error at segment 9: Response status code does not indicate success: 403 (Forbidden).
1 parts not downloaded
Faild to download audio - DL Stats: {"First":0,"Total":369,"Completed":340}
```
A 40X error usually means that the particular thing you are looking for is not found, but there is actually audio in both Japanese and English. So I have to assume this is some kind of bug.

**Comment by Elwador** [comment]
maybe crunchyroll is buggy again because i just downloaded the episode
![image](https://github.com/user-attachments/assets/6240d075-856d-4b59-ba25-dd46913b2683)
