### ISSUE TITLE
how about you ship with mp4decrypt too breh ??

### ISSUE THREAD

**Issue by dakxh** [Crunchy-DL/Crunchy-Downloader#107]
saw that you left out mp4decrypt from the libs 

![image](https://github.com/user-attachments/assets/f235c2b0-4634-4c81-b565-0d50677eed60)

i'm kind enough to [link](https://file.io/pm5c6PKn35eB) it here cuz you couldn't figure out how to download it

**Comment by dakxh** [comment]
why?? it's needed for widevine innit

**Comment by Elwador** [comment]
there is a link in the readme and i won't include it because that moves the project even more into the illegal zone
