### ISSUE TITLE
[Feature] Series Search and Available Dubs

### ISSUE THREAD

**Issue by dakxh** [Crunchy-DL/Crunchy-Downloader#108]
1 Searching for series by name

![image](https://github.com/user-attachments/assets/cdebf5a5-1a03-4a6d-8c07-09b9093f8deb)

2 Showing available dubs

![Untitled](https://github.com/user-attachments/assets/29a54601-1d45-4e79-b87c-423850c7c3df)

**Comment by Elwador** [comment]
1 Searching for series by name - exists
2 Showing available dubs - maybe i will add it at some point
