### ISSUE TITLE
[Feature] Option to disable Muxing and language TAGS

### ISSUE THREAD

**Issue by joekerr-haha** [Crunchy-DL/Crunchy-Downloader#109]
I think an option to not perform muxing after download/decryption would be interesting.
Another thing related to language tags, leave it original, for example:
"zzz.en-US.ass "
"zzz.es-419.ass"
"zzz.es-ES.ass"
"zzz.it-IT.ass"

**Comment by okaneyo** [comment]
Muxing takes about 90 seconds on audio only downloads.. (I'm going back to download English dubs) It's taking forever.. I'm trying to download the project to do a PR but it seems to be missing the csproj file
