### ISSUE TITLE
Login does not work

### ISSUE THREAD

**Issue by Vorffeed** [Crunchy-DL/Crunchy-Downloader#11]
I have a premium account and when I log in to the programme it tells me that the subscription is not active.

![image](https://github.com/Crunchy-DL/Crunchy-Downloader/assets/10000442/1e50dc50-2b4f-4d95-92b5-0e72b80f97e7)

![image](https://github.com/Crunchy-DL/Crunchy-Downloader/assets/10000442/c053981f-ac36-4f90-89d8-0dd90fba649c)

**Comment by Elwador** [comment]
interesting how many edge cases there are with the subscriptions apparently - did you subscribe over the webpage or in a different way?
[what is shown on this page?](https://www.crunchyroll.com/account/membership)
do you have a subscription that is somehow related to something from funimation?

**Comment by Vorffeed** [comment]
I subscribed through the website with the purchase of a 12 month subscription code.
![image](https://github.com/Crunchy-DL/Crunchy-Downloader/assets/10000442/e50d5f1e-444f-4ac9-a2d7-52e188b1d46f)

**Comment by Elwador** [comment]
The new version can now detect Gift Card subscriptions as well - that should solve your problem

**Comment by Vorffeed** [comment]
thanks, it's going perfect
