### ISSUE TITLE
Before you open a new issue

### ISSUE THREAD

**Issue by Elwador** [Crunchy-DL/Crunchy-Downloader#110]
**Before you open a new issue, please ensure you have done the following:**

1. **Review Closed Issues**
   - Have you reviewed the closed issues to verify if your concern has already been resolved? Many common problems and their solutions are documented there.
   - [Search Closed Issues](https://github.com/Crunchy-DL/Crunchy-Downloader/issues?q=is%3Aissue+is%3Aclosed)

2. **Consult the Wiki and Discussions**
   - The [Wiki](https://github.com/Crunchy-DL/Crunchy-Downloader/wiki) is a valuable resource for guides and troubleshooting steps.
   - The [Discussions](https://github.com/Crunchy-DL/Crunchy-Downloader/discussions) section is also a great place to see if others have encountered and resolved similar issues.

3. **Enable Log Mode and Review for Errors**
   - If the program displays an error or behaves unexpectedly, please enable log mode and review the logs for any error messages. Include these logs in your issue submission.

4. **Check the Windows Event Log (if the program crashes)**
   - In the event of a program crash, please check the Windows Event Log for any related error messages (.NET runtime) and include that information in your report.

**Please Note:** Feature requests or issues that have already been addressed will be closed without further comment.

**Comment by dakxh** [comment]
i checked all that, but there ain't no search by name and ain't no available dubs
