### ISSUE TITLE
Feature Addon : Separated Folder For Each Series

### ISSUE THREAD

**Issue by R4H4T069** [Crunchy-DL/Crunchy-Downloader#117]
Your Program Is Working Smoothly . But It will be lot  helpful for me . if there is a feature where when i start to download a series it will create a new folder according to series name. and save the related video and subtitles on that folder

**Comment by Elwador** [comment]
has been answered a bunch of times and also is written in the wiki how to do it

**Comment by R4H4T069** [comment]
> has been answered a bunch of times and also is written in the wiki how to do it

bro i can change file name through file name settings. but didn't saw any thing in wiki that related to create a new folder acording to series name

**Comment by R4H4T069** [comment]
ohh .. okh i get it . i should use \\\ for folder
