### ISSUE TITLE
[Suggest] Allow disable http proxy auto detect.

### ISSUE THREAD

**Issue by eebssk1** [Crunchy-DL/Crunchy-Downloader#123]
Currently the application always uses system proxy settings. This is fine on most scenary.
However On my setup. I have a global system proxy enabled. But for CDL, I use a hook/wfp based proxy software to hijack its connection(because it uses a seprated proxy server made for CDL).
It's impossible to access system proxy through hijacked connection since this means access a proxy through another proxy.
Though CDL seems auto fallback to normal connection without proxy when it can't be accessed, it still better to do NOT do this at first place.

**Comment by Elwador** [comment]
Would be easier to know what software you are using - and how i could replicate your "problem" to help you
