### ISSUE TITLE
Custom font for subtitles

### ISSUE THREAD

**Issue by dakxh** [Crunchy-DL/Crunchy-Downloader#127]
The current font for subtitles is [Trebuchet MS](https://www.cufonfonts.com/font/trebuchet-ms-2), it's cool to choose whatever font to apply to the subtitles like [Arial](https://www.myfonts.com/collections/arial-font-monotype-imaging), [Verdana](https://www.myfonts.com/collections/verdana-font-microsoft-corporation) and [Consolas](https://www.myfonts.com/collections/consolas-font-microsoft-corporation).

Or is there a way to do that already ??

**Comment by BattouKen** [comment]
> **[dakxh](/dakxh) ** commented

lo mas sencillo es descargar y usar Aegisub, es bastante sencillo de ocupar para lo que tu deseas.

![image](https://github.com/user-attachments/assets/32d1f465-cb34-4c73-af2e-d6c4b9ac489b)

**Comment by dakxh** [comment]
yeah I'm aware of SubtitleEdit and AegiSub, but I would prefer if it was somehow integrated into the Downloader

**Comment by Elwador** [comment]
if at all, I will only add this feature for closed captions (CC) subtitles

**Comment by 21R01A7263** [comment]
very much appreciated 👍🏻
