### ISSUE TITLE
¿Podrían implementarse nuevas funciones?

### ISSUE THREAD

**Issue by Vorffeed** [Crunchy-DL/Crunchy-Downloader#13]
First of all, thank you very much for the program, it has everything that I was looking for. Although, if you could implement some of this, it would be perfect for me.

1º Select the default calendar region in options, as by default it always opens in De every time you close and open the programme and I have to change it to es-Es all the time.

2º I haven't seen this and I don't know if it's somewhere but apart from the download path option, it would be nice to have another option to activate whether or not you want to save the episodes separated by folders with the name of the series, so if you download different episodes each one will be saved in its corresponding folder and so you can have all the videos organised of the same series in the same folder and not all the single videos of different series in the same folder.

3rd One option could be implemented in the separate subtitles option of the video that when there is only one subtitle to download, because I doubt that the majority select all the subtitles to download, it is identical to the name of the video, that is, the number or the region of the subtitle does not appear at the end, since I always like to make sure that the downloaded subtitle corresponds to the video, because chrunchy often messes up and puts subtitles from other episodes by mistake or incomplete and so I only download the subtitle when they fix it and not the video again and when everything is fine I remux with a .bat.

**Comment by Elwador** [comment]
1 - yes i can implement that in a future release

2 - technically it works if you just put the ${series-title} with a \\\ in front of the file name - but i haven't tried that before and it currently creates an additional empty folder in the application folder - i will improve that in an upcoming release
![image](https://github.com/Crunchy-DL/Crunchy-Downloader/assets/75888166/5efeba3b-3d4d-42cc-aed6-ab180d110c8e)
in the history view, if you have it enabled, you can set a download path for each series & also for each season of a series

3 - so if i understood you correctly you want that if only one subtitle is selected to be downloaded in the settings the name shouldn't be like `A Salad Bowl of Eccentrics - S01E03.01.eng.ass` but `A Salad Bowl of Eccentrics - S01E03.ass` - if yes i can do that (and maybe already have done it while writing this ^^)

**Comment by Vorffeed** [comment]
thanks, If point 3 was what I was referring to, I will try point 2 to see if that is what he believes.

**Comment by Vorffeed** [comment]
I have tried what you said in point two and it works, thank you 👍

**Comment by Elwador** [comment]
@Vorffeed i released the new version with the changes
