### ISSUE TITLE
History doesn't work correctly if episode description language is changed

### ISSUE THREAD

**Issue by deso85** [Crunchy-DL/Crunchy-Downloader#134]
I am pretty sure it worked before but now I've got an issue with the history view.

When I change the **episode description language** (Muxing settings) the search screen shows results in that language. That is good even if I guess it should be somehow different as search is not part of the muxing process.

I don't know for sure but I guess all search results were in english when I first started the app. After I switched to another language the search results were in that language. When choosing an anime it was added to the history with the language I chose. After the update all information is not stored correctly and is missing.

Search (German results): 
![image](https://github.com/user-attachments/assets/6eac8052-5b58-43e6-baa3-4b934b25b5d9)

History:
![image](https://github.com/user-attachments/assets/240996b5-57f8-49ff-a325-8ff9ff7ae118)

Details:
![image](https://github.com/user-attachments/assets/36f0e978-56db-4319-9b35-9f4d3fbbe95d)

After I restarted the app it seems to work correctly. But if I change back to default or en-US it wont change anything. At first the bug with missing informations occurs. After a restart it works again but it always shows me German results even if I changed the language.

Am I wrong and it was always shown in German as my IP is located in Germany or am I right and it's somehow bugged?

**Comment by Elwador** [comment]
episode description language (Muxing settings) - has nothing to do with what language is shown in the history or the search results
only the history language has an impact on that

**Comment by deso85** [comment]
When I change that language it breaks the history as shown in the screenshots. Maybe it is related somehow?

**Comment by Elwador** [comment]
no the description language is only used in the download process to decide what language the description should be that is put in the meta data of the video file

this has is used for search/history language
![image](https://github.com/user-attachments/assets/633840a9-98c4-400e-b716-6a85209b2f5c)

i also just tried changing the description language and nothing changed - maybe enable log mode

**Comment by deso85** [comment]
I enabled log mode but it is not as helpful as i could be. After a restart which always have to be performed after changing settings to be really sure:
```
Log mode enabled.
Log mode enabled.
No proxy is being used.
```
Maybe a short video clip shows the whole procedure:

https://github.com/user-attachments/assets/1d7b826c-db61-4226-85f1-7e76d3e770f6

**Comment by Elwador** [comment]
the problem has nothing to do with the description language - it is that if you search for a series go somewhere else and for example remove the series from the history i still keep the series cached in the search and don't send a new request to CR 
so if you search for a different series and then serach for nier again it will show like normal

**Comment by deso85** [comment]
I dont get the point. Even if it has nothing to do with this explicit setting the history seems to be bugged - in my example when I change the language. The correct behaviour of the history view would be that the cover and information can be shown.

**Comment by Elwador** [comment]
Yes, it is a bug, but it's not very serious since it only occurs when someone adds a series, removes it, and adds it again without searching for a different series or restarting in between

**Comment by deso85** [comment]
Ok, with that description I was able to reproduce it. I agree, it is not serious and doesn't need to be fixed quickly. Thanks for the fast replies!
