### ISSUE TITLE
The update button remains active all the time.

### ISSUE THREAD

**Issue by rifatozkancomtr** [Crunchy-DL/Crunchy-Downloader#139]
The update button remains active all the time.

![image](https://github.com/user-attachments/assets/d41e3877-40d4-4a03-8b3f-f7c139f09e58)

**Comment by Vorffeed** [comment]
It is normal because if you look, the version in configuration, you have not been updated, there is a problem with this version that does not apply the update correctly and you have to do it manually, is what happened to me too.

**Comment by Elwador** [comment]
yes forgot that the old version can't handle multiple versions when updating and it downloaded the linux version for you
you probably have some .so files in your downloader folder you can safely remove those
i changed the release and moved the linux/macos versions to a pre-release so now it works again
