### ISSUE TITLE
Doubt about episode numbering

### ISSUE THREAD

**Issue by Vorffeed** [Crunchy-DL/Crunchy-Downloader#14]
First of all, thank you very much for the above modifications.🥰

Is there any way to put in the episode name format code that is numbered from 0 to 9, because there are some that number them as 0 as well, to add a 0 in front to have two digits in the numbering of the initial numbers.

that is, 00, 01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, etc... and thus have an even numbering

**Comment by Elwador** [comment]
sry but i don't quit understand what you mean - there is currently already a setting that alows to define how many leading 0 there are so that episode 1 is not 1 but 01 or if it is set to 3 leading zeros 001

**Comment by Vorffeed** [comment]
Sorry, I was blind and didn't see that it was just above the name setting.🤦‍♀️
