### ISSUE TITLE
Unable to download files with very long names.

### ISSUE THREAD

**Issue by NeonShogun404** [Crunchy-DL/Crunchy-Downloader#140]
Hello, first of all, congratulations to the creator for the program. It's incredible how well it works.
Now the problem I've encountered:
I'm downloading the anime "The Family Circumstances of the Irregular Witch". Episode 11 can't be downloaded with the configuration I have for the current renaming, that is:
${seriesTitle}\\S${season}\\S${season}E${episode} - ${title} [${height}p] [${dubs}]

![image](https://github.com/user-attachments/assets/8e2ab484-c08f-49ca-95bc-a7d5415dc7fe)

I know the error is that the title is too long, because I've tried with this configuration:
${seriesTitle}\\S${season}\\S${season}E${episode} - [${height}p] [${dubs}]
and the episode has been downloaded.

![image](https://github.com/user-attachments/assets/a9f769a8-5433-45c9-b6ec-79972f7280b2)

I would like there to be an option in the program's configuration that allows setting a maximum number of characters in the file title. This would help with animes like this that have very long names.
Thanks.

**Comment by Elwador** [comment]
i had no problem downloading the episode with `${seriesTitle}\\S${season}\\S${season}E${episode} - ${title} [${height}p] [${dubs}]` but you are right there is a limit how long the file name can be
can you please test it with [v1.5.36.1](https://github.com/Crunchy-DL/Crunchy-Downloader/releases/tag/v1.5.36.1)

**Comment by NeonShogun404** [comment]
I have tried on 2 PCs.
On the first one it still won't let me download the file. In other words: it downloads, decrypts and when it is muxed it disappears. I noticed that on this PC the language in which the title appears is English (and the title is very long).

![image](https://github.com/user-attachments/assets/539239da-1e86-4dba-ae5d-570d0a0c242e)

![image](https://github.com/user-attachments/assets/d2af43bb-9f0b-4bf2-add8-4b4b9a3bf366)

![image](https://github.com/user-attachments/assets/944a7de5-d7c1-4b29-ac02-1af6c83ee465)

On the other PC it did let me download it in one go. In this case the title appears in Spanish and is much shorter in terms of characters.

![image](https://github.com/user-attachments/assets/b7b42330-acf4-4798-8086-0fa63c80a0f3)

![image](https://github.com/user-attachments/assets/62194376-b03b-433d-90e1-cc0003893cac)

If you ask me, I don't know why the titles appear in English on one PC and in Spanish on the other.

**Comment by Elwador** [comment]
the different language is probably that on one pc you have changed the history language 

the [v1.5.36.1](https://github.com/Crunchy-DL/Crunchy-Downloader/releases/tag/v1.5.36.1) should shorten the name to a length that should work fine 

i updated the [v1.5.36.1](https://github.com/Crunchy-DL/Crunchy-Downloader/releases/tag/v1.5.36.1) with some debug messages maybe try to enable the log mode and see if it says that the filename is to long 

i also tried it with the english title and even with the v1.5.36 it works 😆 so kind of strange that it doesn't work for you

**Comment by Elwador** [comment]
i updated the [v1.5.36.1](https://github.com/Crunchy-DL/Crunchy-Downloader/releases/tag/v1.5.36.1) release - it now also works when i disable windows long file paths

**Comment by NeonShogun404** [comment]
I tried again and this time I was able to download the episode with the title in English.

![image](https://github.com/user-attachments/assets/79fc4c14-1b16-44ac-94ed-e30e9b2e746d)

By the way, the language issue was because of what you mentioned (I had Spanish assigned in the history of the other PC).

Thank you very much.
