### ISSUE TITLE
Default calendar.

### ISSUE THREAD

**Issue by nigoki2** [Crunchy-DL/Crunchy-Downloader#141]
Hi. The default calendar doesn't show anything since a couple of days
![Capture1](https://github.com/user-attachments/assets/ada61088-055f-4129-84a4-af0bd18ae360)
Only the custom calendar works.
![Capture2](https://github.com/user-attachments/assets/a38879a9-205a-4100-ba15-2c44d5a32ee5)
It's not a big trouble, but I prefer the default one.
Thank you for tou work!

**Comment by Elwador** [comment]
cloudflare issue - so it depends on your connection if it works or not
