### ISSUE TITLE
When I say refresh the filter, it gets stuck.

### ISSUE THREAD

**Issue by rifatozkancomtr** [Crunchy-DL/Crunchy-Downloader#142]
![image](https://github.com/user-attachments/assets/55441fd7-dafb-4d8f-afb7-0ddfe05dc3d7)

When I say refresh the filter, it gets stuck.

log : 

Log mode enabled.
No proxy is being used.
Season is empty!

**Comment by rifatozkancomtr** [comment]
The problem was fixed when I deleted After-School Hanako-Kun.

**Comment by Elwador** [comment]
is fixed in the new version

**Comment by rifatozkancomtr** [comment]
> is fixed in the new version

thank you.
