### ISSUE TITLE
The application does not open full screen, only the icon is visible.

### ISSUE THREAD

**Issue by rifatozkancomtr** [Crunchy-DL/Crunchy-Downloader#143]
The application does not open full screen, only the icon is visible.
I reinstalled the latest update but the same problem persists.
The application opens but it is not full screen and no image appears on the screen.

![image](https://github.com/user-attachments/assets/1e2c3bb3-6d69-4d26-9da9-6ec392ec8d0a)

**Comment by Elwador** [comment]
i couldn't reproduce the issue - could you please provide detailed steps to reproduce it?

also for now just delete the window settings in the config folder and you should be able to start the downloader

**Comment by loddar66** [comment]
did you try to maximize the window (right-click on the small preview...)?

**Comment by rifatozkancomtr** [comment]
> did you try to maximize the window (right-click on the small preview...)?

All I had to do was delete the window settings in the config folder.
