### ISSUE TITLE
Download Error - Too many active streams

### ISSUE THREAD

**Issue by petenun** [Crunchy-DL/Crunchy-Downloader#15]
Trying out the 1.4.24 release and receive the message "Download Error - Too many active streams that couldn't be stopped" when trying to download from queue, whether individually or by simultaneously.

![image](https://github.com/Crunchy-DL/Crunchy-Downloader/assets/55004359/eb45e9ff-ad80-41ae-89e3-f6ff5008c9dc)

**Comment by petenun** [comment]
It looks like the problem was transitory and started working after 10 minutes, but thought I'd leave the case here in case you want to investigate.

**Comment by Elwador** [comment]
make sure to not have crunchyroll streams open in the browser and maybe also close the browser and try again after some minutes - for some reason i can't close sessions when they are from browsers

**Comment by petenun** [comment]
Good to know. And that's exactly what happened - I closed the browser while waiting to re-try.
