### ISSUE TITLE
Error:

### ISSUE THREAD

**Issue by Wernouxe** [Crunchy-DL/Crunchy-Downloader#150]
```
Error: System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at CRD.Utils.HttpClientReq.SendHttpRequest(HttpRequestMessage request) 
 Response: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>SJSTDMMZNBS1V4SJ</RequestId><HostId>sVwRdLj+KWC877qZ8kO+t92ykUQdJOGm5zfKIy0pdqWfOpXyUUz4fETitcRHU1YLMVneBQGf2lc=</HostId></Error>
```

**Comment by eebssk1** [comment]
That's (mostly) means crunchyroll saw you suspicious.

Try change vpn to a less used one.
Try log out, restart app ,log in again.
Try switch account.
Also check if you can access in web normally.

**Comment by Elwador** [comment]
more information would be good - like: when did this happen? did something not work when this error appeared? was the next line in the log that the chapter request failed?

**Comment by josefredohd** [comment]
I got the same message when I try to log in, I'm using a VPS, but is weird because I can access to crunchyroll using the firefox browser

**Comment by josefredohd** [comment]
@Elwador How can I fix that? I can access to my crunchyroll account using firefox, I'm trying using FlareSolverr, but I have not been successful
