### ISSUE TITLE
History "Posters" mode broken?

### ISSUE THREAD

**Issue by loddar66** [Crunchy-DL/Crunchy-Downloader#152]
With the last version (1.5.39) I cannot use the "Posters" mode more than once.

 Usually, I go to the "History" tab, open a certain anime and look for any new episodes matching my language preferences... 
 
![image](https://github.com/user-attachments/assets/9144c5f0-bc7d-418c-a619-2de407b75df5)

Unfortunately, the "back" button doesn't work anymore. Thus, I must change to e.g. calendar and return to the "History", but then I cannot open the individual animes in "Posters" mode anymore - switching to "Table" mode still works fine, but here I'm missing detailed information about the individual episodes...

![image](https://github.com/user-attachments/assets/14fdf91f-85f7-40d5-bb7f-ee71751a62c2)

Hopefully, this description was clear enough. Logging is enabled, but these activities don't seem to be captured...

**Comment by Elwador** [comment]
maybe redownoad the release [v1.5.39](https://github.com/Crunchy-DL/Crunchy-Downloader/releases/tag/v1.5.39 ) - i had the same problem but it fixed itself 😆

**Comment by loddar66** [comment]
works like a charm, thanks! 👍
