### ISSUE TITLE
[Bug] History problem

### ISSUE THREAD

**Issue by Vorffeed** [Crunchy-DL/Crunchy-Downloader#154]
I just realised that if you go into the history to watch a series and then try to go back, it doesn't work and if you click on any other option either the calendar tab or downloads to exit when you go back to the history you can't watch any series again either, it's as if the series boxes were disabled, and you have to close and open the programme all the time.

**Comment by Elwador** [comment]
https://github.com/Crunchy-DL/Crunchy-Downloader/issues/152
