### ISSUE TITLE
Request to fix calendar

### ISSUE THREAD

**Issue by Vorffeed** [Crunchy-DL/Crunchy-Downloader#155]
Could you please fix the normal calendar, so that it would work again, because the custom calendar is very cumbersome because it shows series that have nothing to do with what they broadcast in each region, also you get if they upload a series all the episodes of the series one by one and you die looking for which are the daily episodes of that day, also if you hide them to show the current ones you do not get all the episodes of the daily, and let's not talk about the series with Korean or Chinese audio as the only audio, they are considered as if they were dubbing and if you have activated the dubbing box do not appear, when it should not consider them so, with the old calendar this did not happen and showed you everything that came out daily well and being able to hide the dubbing without hiding those in Chinese or Korean as the only original dubbing.

**Comment by Elwador** [comment]
the simulcast calender works totally fine- only if you have cloudflare problems it doesn't and thats not something i will work on soon

but it is always possible to refine the custom calender
