### ISSUE TITLE
Multi DUB Order

### ISSUE THREAD

**Issue by LorenorZorro3000** [Crunchy-DL/Crunchy-Downloader#156]
If I select 2 Dubs e.g. German and Japanese. Then it always takes the Japanese track first.
But I want the German track first.

I have also tried selecting the Japanese track first and then the German track,
but of course the result is the same.

Or is there a setting for the correct order of the audio tracks?

With kind regards LorenorZorro

**Comment by LorenorZorro3000** [comment]
Would that possibly be a feature you would implement? ^^

**Comment by Elwador** [comment]
it will be sorted in the order you selected the subs/dubs in the settings - [v1.5.41](https://github.com/Crunchy-DL/Crunchy-Downloader/releases/tag/v1.5.41)

**Comment by LorenorZorro3000** [comment]
Wow, now it works perfectly.
Thank you so much for integrating the feature!
