### ISSUE TITLE
Ability to filter all anime.

### ISSUE THREAD

**Issue by rifatozkancomtr** [Crunchy-DL/Crunchy-Downloader#157]
https://www.crunchyroll.com/videos/alphabetical 

Can a feature be added to list and filter all anime?

**Comment by Elwador** [comment]
you can already search i will add nothing else
https://github.com/Crunchy-DL/Crunchy-Downloader/wiki/2-%E2%80%90-Add-Downloads-Interface#add-downloads-interface---search
