### ISSUE TITLE
No sub downloaded Dragon Ball Daima

### ISSUE THREAD

**Issue by Fu2chN** [Crunchy-DL/Crunchy-Downloader#158]
No sub downloaded for Dragon Ball Daima.

Thanks for investigating this.

**Comment by Vorffeed** [comment]
Have you tried to check on the web if the subtitles is not embedded in the video?
Because in several regions like in Spain from minute 1 they have put the subtitles embedded in the video.

**Comment by Fu2chN** [comment]
Indeed, the subtitles are well integrated into the video despite the option to choose the subtitles.

Why did they do this on this anime :/

**Comment by Elwador** [comment]
as you noticed there are only the hardsubs available - don't know why crunchyroll did it like this let's hope this doesn't get a trend
