### ISSUE TITLE
I am new

### ISSUE THREAD

**Issue by Konvinillo** [Crunchy-DL/Crunchy-Downloader#16]
Hi! I'm new to this, so I'm lost on the steps to decrypt the DRM.
I don't know what mp4decrypt is and so on. If someone can explain me the more detailed steps it would be great.
In advance, thank you very much.

**Comment by Nelwidio** [comment]
https://www.bento4.com/downloads/ -> download for windows -> under /bin you will find an mp4decrypt.exe -> copy it to /lib
