### ISSUE TITLE
Download Error - Couldn't get DRM encryption keys

### ISSUE THREAD

**Issue by ferivoq** [Crunchy-DL/Crunchy-Downloader#163]
ProtoBuf.ProtoException: Invalid wire-type (7); this usually means you have over-written a file without truncating or setting the length; see https://stackoverflow.com/q/2152978/23354
   at ProtoBuf.ProtoReader.State.ThrowProtoException(String message) in /_/src/protobuf-net.Core/ProtoReader.State.ReadMethods.cs:line 803
   at ProtoBuf.ProtoReader.State.ThrowWireTypeException() in /_/src/protobuf-net.Core/ProtoReader.State.ReadMethods.cs:line 797
   at ProtoBuf.ProtoReader.State.AppendExtensionField(State& writeState) in /_/src/protobuf-net.Core/ProtoReader.State.ReadMethods.cs:line 987
   at ProtoBuf.ProtoReader.State.AppendExtensionDataImpl(IExtension extn) in /_/src/protobuf-net.Core/ProtoReader.State.ReadMethods.cs:line 908
   at ProtoBuf.ProtoReader.State.AppendExtensionData(IExtensible instance) in /_/src/protobuf-net.Core/ProtoReader.State.ReadMethods.cs:line 883
   at proto_2(State&, ClientIdentification)
   at ProtoBuf.ProtoReader.State.ReadAsRoot[T](T value, ISerializer`1 serializer) in /_/src/protobuf-net.Core/ProtoReader.State.ReadMethods.cs:line 1157
   at ProtoBuf.ProtoReader.State.DeserializeRoot[T](T value, ISerializer`1 serializer) in /_/src/protobuf-net.Core/ProtoReader.State.ReadMethods.cs:line 1137
   at ProtoBuf.Serializer.Deserialize[T](Stream source) in /_/src/protobuf-net/Serializer.Deserialize.cs:line 20
   at CRD.Utils.DRM.Session..ctor(ContentDecryptionModule contentDecryptionModule, Byte[] pssh)
   at CRD.Utils.DRM.Widevine.getKeys(String pssh, String licenseServer, Dictionary`2 authData)
Failed to get encryption keys

I got the client id and key from virutal device.

**Comment by codetolearner** [comment]
I also got the download error as well. see image

![8DdoxTe](https://github.com/user-attachments/assets/7812fe26-553c-4b38-a873-5ee8f46e92ed)

**Comment by Akczht** [comment]
check whether you have enabled mature content for your account

**Comment by Elwador** [comment]
> ProtoBuf.ProtoException: Invalid wire-type (7); this usually means you have over-written a file without truncating or setting the length; see https://stackoverflow.com/q/2152978/23354 at ProtoBuf.ProtoReader.State.ThrowProtoException(String message) in / _/src/protobuf-net.Core/ProtoReader.State.ReadMethods.cs:line 803 at ProtoBuf. ProtoReader.State.ThrowWireTypeException() in /_ /src/protobuf-net.Core/ProtoReader.State.ReadMethods.cs:line 797 at ProtoBuf.ProtoReader.State.AppendExtensionField(State& writeState) in / _/src/protobuf-net.Core/ProtoReader.State.ReadMethods.cs: line 987 at ProtoBuf.ProtoReader.State.AppendExtensionDataImpl(IExtension extn) in /_ /src/protobuf-net.Core/ProtoReader.State.ReadMethods.cs:line 908 at ProtoBuf.ProtoReader.State.AppendExtensionData(IEtensible instance) in / _/src/protobuf-net.Core/ProtoReader.State.ReadMethods.cs :line 883 at proto_2(State&, ClientIdentification) at ProtoBuf.ProtoReader.State.ReadAsRoot[T](T value, ISerializer `1 serializer) in /_/src/protobuf-net.Core/ProtoReader.State.ReadMethods.cs:line 1157 at ProtoBuf.ProtoReader.State.DeserializeRoot[T](T value, ISerializer`1 serializer) in /_ /src/protobuf-net.Core/ProtoReader.State.ReadMethods.cs:line 1137 at ProtoBuf.Serializer.Deserialize[T](Stream source) in /_/src/protobuf-net/Serializer.Deserialize.cs:line 20 at CRD.Utils.DRM.Session..ctor(ContentDecryptionModule contentDecryptionModule, Byte[] pssh) at CRD.Utils.DRM.Widevine.getKeys(String pssh, String licenseServer, Dictionary`2 authData) Failed to get encryption keys
> 
> I got the client id and key from virtual device.

the initial problem in this issue was solved by redownloading the downloader from github 

> I also got the download error as well. see image
> 
> ![8DdoxTe](https://private-user-images.githubusercontent.com/80784058/380540238-7812fe26-553c-4b38-a873-5ee8f46e92ed.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3MTIyOTksIm5iZiI6MTczMTcxMTk5OSwicGF0aCI6Ii84MDc4NDA1OC8zODA1NDAyMzgtNzgxMmZlMjYtNTUzYy00YjM4LWE4NzMtNWVlOGY0NmU5MmVkLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQyMzA2MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTQwMzc1NTNiMDZhNDY1MzFiMDcyZmJjMjlmYTQ4YzQ5ODdmODZmZWU3YzUwMmU0ZmIwNjcxN2I1NTJmM2Q5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.x79Tp_7vXORcGxnYc4pejF3bzOqG29Ncz0azKEfoOVo)
> 
> ![DehtHQB](https://private-user-images.githubusercontent.com/80784058/380540709-208b42c8-5f5d-4d22-9798-081bacfc1027.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3MTIyOTksIm5iZiI6MTczMTcxMTk5OSwicGF0aCI6Ii84MDc4NDA1OC8zODA1NDA3MDktMjA4YjQyYzgtNWY1ZC00ZDIyLTk3OTgtMDgxYmFjZmMxMDI3LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQyMzA2MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YTgzNmIwYTk3ZTFhOGUxM2M1ODczYTk0N2NkNjUyYjYzYTVjODUyYjA4YjhkMTNjODhlNzM0MWUxYTEzOTBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fRRkzA1pVEEqx8BLVimXD3_P7N1L8khyZ7ypX6jCCag)

this is probably something else but it would be necessary to see the log output
