### ISSUE TITLE
[Doubt] Could this be implemented

### ISSUE THREAD

**Issue by Vorffeed** [Crunchy-DL/Crunchy-Downloader#165]
Would you open the possibility of implementing in the history menu the possibility of forcing the videos of that particular series to be downloaded in a certain resolution independently of the general resolution that you have configured as it happens with the selection of forcing audio and subtitles? 

It is that not all the series I download with the same resolution and I have to change all the time the properties from configuration and sometimes I forget to revert the change and I have already messed it up, having to download again everything that I had already downloaded during the week ><

**Comment by Elwador** [comment]
should be now in the newest version
