### ISSUE TITLE
no entiendo algo de la actualizacion 1.5.40

### ISSUE THREAD

**Issue by BattouKen** [Crunchy-DL/Crunchy-Downloader#168]
`Added functionality to combine multiple episodes from the same season into a single entry.`

![image](https://github.com/user-attachments/assets/34813281-437e-4662-ac5b-63d45e12b74d)

entendí algo como que se agregó el poder descargar por ej. del episodio 50 al 150 si es que no me interesa bajar del 1 al 49 ? porque si es así seria genial, pero no entiendo como funciona y si es otra cosa me disculpo por poner este ticket.

**Comment by Vorffeed** [comment]
A ver, no.
Esta funcionalidad lo que hace es agrupar las tandas de episodios que publican simultáneamente de una serie, es decir que si publican de una tacada una serie entera de 12 episodios o 4-5 episodios de esa serie no vas a ver en el calendario 12 pestañas o 4-5  pestañas con cada uno de esos episodios, porque sino para encontrar los episodios de otras series publicados el mismo dia es un caos porque salen mezclados y te pierdes, con esto te los agrupa y al darle te los pone en cola todos los episodios de esa serie subido ese dia, sino han publicado los anteriores ese dia desde ahi es imposible descargarlos porque los habrán publicado otro dias, pero para eso ya tienes el historial que ahi si te salen todos los episodios que se han ido publicando y se van añadiendo con forme salen

**Comment by BattouKen** [comment]
uff que lastima, yo que pensé que porfin habra agregado que se puediera por ejemplo descargar de por ej. episodio 20 al 25 por decir alguna, que lastima porque si yo quisiera hacer eso tendria que si o si ó marcar todos los que quiero que capas quiero bajar one piece del 100 al 200 y tendria que marcar 100 episodios manualmente... en fin, cerraré el tema entonces.

**Comment by Elwador** [comment]
> And I thought they had finally added the option to download, for example, episodes 20 to 25, for example, which is a shame, because if I wanted to do that, I would have to either mark all the ones I wanted, or maybe I want to download One Piece from 100 to 200 and I would have to mark 100 episodes manually... anyway, I'll close the topic then.

you can always use the "Add Downloads" tab you can even mark multiple episodes with SHIFT + CLICK there so there is no need to add a range add anywhere

**Comment by BattouKen** [comment]
> > And I thought they had finally added the option to download, for example, episodes 20 to 25, for example, which is a shame, because if I wanted to do that, I would have to either mark all the ones I wanted, or maybe I want to download One Piece from 100 to 200 and I would have to mark 100 episodes manually... anyway, I'll close the topic then.
> 
> you can always use the "Add Downloads" tab you can even mark multiple episodes with SHIFT + CLICK there so there is no need to add a range add anywhere

oooh, pero si en versiones anteriores no se podria, desde cuando se puede? bueno lo importante es que ya puedo, gracias. 👍💯
