### ISSUE TITLE
Softsubs not dowloading and/or muxing for multiple languages

### ISSUE THREAD

**Issue by Symptomaker** [Crunchy-DL/Crunchy-Downloader#171]
Title says it all. Is this a bug or intended?

Screenshots of my download settings are attached:

![image](https://github.com/user-attachments/assets/b8f21a4a-b37f-476d-a3d7-8e8a3baf6dbe)

![image](https://github.com/user-attachments/assets/2a9f8ad9-d82c-49e8-a461-a5331a9433e6)

![image](https://github.com/user-attachments/assets/830a2190-60bc-46b1-9204-9d6d0cad7620)

![image](https://github.com/user-attachments/assets/f59f75dd-9588-4fcc-9af1-fbd7be6c086a)

![image](https://github.com/user-attachments/assets/2dac51f2-f858-4d51-aeb7-5fc42834957a)

![image](https://github.com/user-attachments/assets/bf31128c-e708-4ed6-a3a8-3d8438a05b66)

**Comment by Elwador** [comment]
no your settings should work - and with similar settings it also works fine for me 
maybe enable log mode or download the downloader again from github [v1.5.42](https://github.com/Crunchy-DL/Crunchy-Downloader/releases/tag/v1.5.42)

<details>

<summary>Images</summary>

![image](https://github.com/user-attachments/assets/461e82ed-c1fa-49d7-85d6-6d0c87325714)
![image](https://github.com/user-attachments/assets/6334a871-c6ab-493c-aa0a-60954e938c2b)
</details>

**Comment by Symptomaker** [comment]
Redownloading seems to have fixed the problem. Thanks!
