### ISSUE TITLE
To create a folder structure for series, season, and episode

### ISSUE THREAD

**Issue by shoyrock** [Crunchy-DL/Crunchy-Downloader#173]
Hi, I don’t know if I’m the one doing something wrong. I’ve been trying to create a folder structure to keep all the videos separated and organized, but I haven’t had any luck. This is what I’ve been trying to use to organize the files.
{Series Title} - S{season:00}E{episode:00} - {Episode Title} {Quality Full}

**Comment by Elwador** [comment]
https://github.com/Crunchy-DL/Crunchy-Downloader/wiki/5-%E2%80%90-Settings#filename-settings

**Comment by shoyrock** [comment]
thanks i just tested using ${seriesTitle}\\Season ${season}\\${seriesTitle} - S${season}E${episode} - ${title} [${height}p]
and it seems to be working

**Comment by rifatozkancomtr** [comment]
> thanks i just tested using ${seriesTitle}\Season ${season}\${seriesTitle} - S${season}E${episode} - ${title} [${height}p] and it seems to be working

\\${seriesTitle}\\Season ${season}\\${seriesTitle} - S${season}E${episode}
