### ISSUE TITLE
Couldn't add episode to the queue

### ISSUE THREAD

**Issue by x3inspire** [Crunchy-DL/Crunchy-Downloader#174]
Hi, may i know why i cannot add to que for these series?

[https://www.crunchyroll.com/series/GP5HJ8E81/link-click?srsltid=AfmBOooau36WQUCPKpazuDAqGKRU_rTd2z0yGF3fq80pKIqFhqZCQIrk](url)

![image](https://github.com/user-attachments/assets/7db51522-913f-43f3-8fa1-45f543a3b9ce)

![image](https://github.com/user-attachments/assets/8f80087a-57f4-4f2b-a1ce-fbb42242024f)

**Comment by Vorffeed** [comment]
It is as simple as you have set Japanese as the main language in your rules, and this series does not have Japanese as the main language, but Chinese.
In these cases you have to go to the series tab in the history and there tell it that the main language of that series is Chinese.
