### ISSUE TITLE
Audio out of sync

### ISSUE THREAD

**Issue by eastoncrafter** [Crunchy-DL/Crunchy-Downloader#178]
Video streams seem to be missing the funimation/Crunchyroll intro, which then makes the audio stream off by about 8 seconds. Any fix?
Lmk if more info is needed

**Comment by Elwador** [comment]
as said at the dubs:
![image](https://github.com/user-attachments/assets/307c15fa-106c-4d13-9f27-9433a1aa087e)
but you can try
![image](https://github.com/user-attachments/assets/cd197102-b43b-4603-ab16-7bad9f386b27)

**Comment by eastoncrafter** [comment]
Sync timings doesn't actually work, but eliminating the Japanese language seemed to fix it. I think a fix to this would be allowing people to configure the video streams grabbed by which language the video streams are for. Seems like the funimation intro is only on the English language video but not the Japanese video. Is there a way to add an offset to the Japanese audio? (Assuming that eventually a feature to configure priority video is added at some point)
