### ISSUE TITLE
Adding contribution

### ISSUE THREAD

**Issue by ricoloic** [Crunchy-DL/Crunchy-Downloader#181]
Would it be possible for you to add the information on how to build the application our self. Having that information would facilitate the contribution from others to the repo.

**Comment by Elwador** [comment]
There is already a build guide available in the wiki, which outlines the steps for building the application.

As for contributions, I generally don’t accept pull requests to the project. However, if you notice any issues or areas where the downloader could be improved, please feel free to suggest enhancements or raise an issue in the repo.

**Comment by ricoloic** [comment]
Awsome thank you didn't notice the building steps before, I'll be checking them out. Thanks for mentioning!
