### ISSUE TITLE
[Question] Update Repo Code

### ISSUE THREAD

**Issue by Jettcodey** [Crunchy-DL/Crunchy-Downloader#183]
Hey @Elwador,
I've noticed that since Release 1.51, no new commits have been pushed to the repo. Is there any reason why you suddenly stopped pushing code? It would be great if the latest changes could be pushed to the repo!

**Comment by Elwador** [comment]
the main reason is that maintaining and updating multiple repositories consistently can sometimes fall behind due to prioritization of other task but i have now updated it to the v1.5.43 release.

**Comment by Jettcodey** [comment]
Makes Sense,, but thanks for updating
