### ISSUE TITLE
About the way of displaying series with the New Calendar

### ISSUE THREAD

**Issue by Vorffeed** [Crunchy-DL/Crunchy-Downloader#186]
Is there any way for the calendar to show the series in your region?
Because with the implementation of the new calendar there are series that are not in my region, nor the schedules are the same and it has already happened to me that I have skipped episodes because when the day passes if they are all, but as I look throughout the day there are episodes that have come out with another schedule as they appear in the calendar sorted and of course those episodes I skip them because they appear later and then appear sorted above the one I already have downloaded when here that has come out before the other that said it came out before, skipping those episodes for not realizing.

Apart from watching episodes that are not available in my region and having to scroll to the ones that are  available in my region.

![image](https://github.com/user-attachments/assets/0f308a8c-7137-4f71-8a5f-123a6fba87ba)![image](https://github.com/user-attachments/assets/3a2037c1-2857-4427-91b0-c744a2b00486)

As you can see the one of love live, that if this in my region comes out higher than the one of sangri-la but has not been issued yet, apart from the other series that appear as Fayri Tale that is not licensed in my region.

**Comment by Elwador** [comment]
you can always just disable the upcoming episodes - also the times get more accurate if you have the series in the history and refreshed them at least once since the update
i now also changed the sorting
