### ISSUE TITLE
No chapters with dub-language only.

### ISSUE THREAD

**Issue by LorenorZorro3000** [Crunchy-DL/Crunchy-Downloader#188]
I’m using version 1.5.43 (Windows).

When I download a German-dubbed episode, there are no chapters included. However, if I download the same episode in Japanese dub (even if the German dub is also included), chapters are present.

Example links:

https://www.crunchyroll.com/de/series/GNVHKN903/ron-kamonohashis-forbidden-deductions
https://www.crunchyroll.com/de/series/GZJH3D719/tsukimichi--moonlit-fantasy-  **Season 2, Episodes 13–25**

**Comment by Elwador** [comment]
yes that is how crunchyroll works - it has chapters for the japanese dub but not the german dub

**Comment by LorenorZorro3000** [comment]
For Tsukimichi Season 2, chapters are included for episodes 01–12, but starting from episode 13–25, they are missing.

For Ron Kamonohashi, I only tested the first season in German, and there were no chapters included.

**Comment by Elwador** [comment]
still works fine for these as well

<details>

<summary>MediaInfo</summary>
<img src="https://github.com/user-attachments/assets/cb89ca67-3d40-4f34-95ca-ef50145b045f" alt="Media Info" />
<img src="https://github.com/user-attachments/assets/08c327e5-8cdf-4956-b67b-2e4cec9ce4bd" alt="Media Info" />
</details>

**Comment by LorenorZorro3000** [comment]
Strange... I noticed this on December 19, and the chapters weren’t included back then.
I just tested it again, and now the chapters are there.

Crunchyroll has probably added them in German now.

Thank you for your efforts!

**Comment by Elwador** [comment]
yes crunchyroll is lazy sometimes 🤣 like with [Seirei Gensouki: Spirit Chronicles S2E09](https://www.crunchyroll.com/watch/G4VUWKZ0X/the-battle-to-defend-amande) i don't know if they will ever fix the japanese audio 

but i am glad it works now for you
