### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Vorffeed** [Crunchy-DL/Crunchy-Downloader#21]
Is there any way to adjust the calendar text so that it appears in full and not cut off?
As you have to mouse over the text to see if it is a dubbed version in another language or the one you are looking for.
![image](https://github.com/Crunchy-DL/Crunchy-Downloader/assets/10000442/e46e0d7a-b81c-4a0a-b1df-7264f4e8e953)

Another thing, I have noticed that there is a small problem in the download tab, even if you have activated the auto download button if you do not enter or do not stay in that window the program does not download, or if it was downloading something and you have more files and you decide to go to settings or get into calendar or hsitorial, what you had downloading at that time ends but does not start downloading any new until you return to the tab.

**Comment by Elwador** [comment]
for the calendar i haven't found a way yet to display the complete text without it looking really strange overall

and regarding the download tab it is the intended way how i wanted it but i can see how it can be annoying - will change it in one of the next releases

**Comment by Elwador** [comment]
i just released a new version - [v1.4.27](https://github.com/Crunchy-DL/Crunchy-Downloader/releases/tag/v1.4.27) it should address both issues - the change for the calendar definitely isn't the best solution and it only works for slightly longer names but it should be better
