### ISSUE TITLE
Crunchy-Downloader (1.4.30) exits unexpectedly during refresh.

### ISSUE THREAD

**Issue by petenun** [Crunchy-DL/Crunchy-Downloader#27]
When I click on "Refresh Filtered" in History, the program scans the first five titles and then just exits. I thought it might have been a specific title so I removed that, but it still happens.

I tried it on multiple computers (Windows 10 23H2, no recent updates) and get the same behavior.

I enabled logging, but the only entry in the log file is "Log mode enabled."

If episodes are added individually via "Add Download" button, everything works as expected.

**Comment by Elwador** [comment]
if the programm crashes the error only shows up in the windows event log 
there is a section for aplications and in there should be an error with .net core or something similar

**Comment by petenun** [comment]
Let's see if this helps at all. Both of these occur in the application event log that match my experiences.

![image](https://github.com/Crunchy-DL/Crunchy-Downloader/assets/55004359/ca7076d3-1f15-4488-992e-08b1060942be)

![image](https://github.com/Crunchy-DL/Crunchy-Downloader/assets/55004359/09e067f8-dab5-48b2-8ce8-308085ee19c3)

**Comment by Elwador** [comment]
[v1.4.31](https://github.com/Crunchy-DL/Crunchy-Downloader/releases/tag/v1.4.31) should solve the crashing

**Comment by petenun** [comment]
I just tested it out and it looks like it's working again. You rock!
