### ISSUE TITLE
Crunchyroll Calendar not appearing

### ISSUE THREAD

**Issue by petenun** [Crunchy-DL/Crunchy-Downloader#29]
I've run into an issue where the Crunchyroll release calendar doesn't appear on the calendar tab. The Refresh and language selection box  appear at the top but nothing below. The calendar appears as expected on a different computer. What would be the best way to troubleshoot this?

**Comment by Elwador** [comment]
maybe you get an error in the log mode - but the calendar doesn't do much it more or less only loads the simulcast calendar from crunchyroll 
so as long as the simulcast calendar from crunchroll loads the calendar should load as well

**Comment by petenun** [comment]
The simulcast calendar comes up via chrome browser. Here's what I get in the log:

Log mode enabled.
Error: System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at CRD.Utils.HttpClientReq.SendHttpRequest(HttpRequestMessage request) 
 Response: error to long
No days found in the HTML document.

**Comment by Elwador** [comment]
does this also happen when you press reload on the calendar tab? i usually get that error if i go to the calendar tab right after starting the downloader but reloading or switching tabs usually works to load it afterwards

**Comment by petenun** [comment]
Refresh doesn't work, neither does switching between tabs. 

I just tried copying the entire program and config files from the working computer to the non-working one, and the calendar still doesn't work with identical files. The biggest difference is that the working computer is running Windows 10, and the non-working computer is running Windows Server 2019. I'll have to do some further troubleshooting in the morning. I'll keep you posted.

**Comment by Elwador** [comment]
try it again with the new release maybe it fixes the problem

**Comment by Vorffeed** [comment]
The new update has loaded the calendar xd

**Comment by petenun** [comment]
Installed the new version 1.4.32, but the calendar still does not load (Windows Server 2019)

Log mode enabled.
Error: System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at CRD.Utils.HttpClientReq.SendHttpRequest(HttpRequestMessage request) 
 Response: error to long
No days found in the HTML document.

Calendar appears fine in Chrome (https://www.crunchyroll.com/simulcastcalendar?filter=premium)

**Comment by Vorffeed** [comment]
I have enabled the log, and I get the same message with the new update, for the calendar, instead I go back to the previous version and zero problems.

**Comment by Elwador** [comment]
> The new update has loaded the calendar xd

@Vorffeed but you said it loaded the calendar? - the error also occurs in the older versions but for me it happens very rarely

**Comment by Vorffeed** [comment]
> > The new update has loaded the calendar xd
> 
> @Vorffeed but you said it loaded the calendar? - the error also occurs in the older versions but for me it happens very rarely

I don't think I was understood 😅
I wanted to say that the new update has broken the calendar, I wanted to say load to break and not load to go well, the translator seems to have misunderstood what I wanted to express.

**Comment by Vorffeed** [comment]
In short, the new update causes the calendar to show nothing, while the calendar in the previous version works perfectly.
Could you revert the changes you have made to the calendar part?
And be able to use the new improvements 😉

**Comment by Elwador** [comment]
@Vorffeed should work again in the new v1.4.33 release.

@petenun, the problem with Windows Server 2019 is that Cloudflare blocks the request. While testing, it actually surprised me that it doesn't get blocked on a normal Windows installation 😅. A solution would be to include a browser in the downloader to load the page and get the HTML, but that's a lot of overhead just for this one request. Also, while testing this, the browser had to be opened in a new window, or else it would fail with the same error. Another solution would be to use FlareSolverr - this might be a good way to solve it, but I haven't tried it yet

**Comment by Vorffeed** [comment]
Yes, it's working again, thank you 😉

**Comment by petenun** [comment]
@Elwador Thanks for looking into the Windows Server issue. I can deal with not a calendar. I'm probably an exception in running this as my OS. I do appreciate the explanation as to why it's not working. At least it's not the program itself that is the problem. :-)

**Comment by Elwador** [comment]
@petenun i added a "Custom Calendar" option to the calendar tab that could work for you as well

**Comment by petenun** [comment]
You did it! The calendar now works using the Custom Calendar!! Thank you!

**Comment by petenun** [comment]
Now that I'm able to see the calendar, should the language drop-down filter the calendar to show dub episodes in that language? It's not clear what the language box does, though it does not appear to filter any calendar contents. Also, it appears that selecting the Custom Calendar checkbox works, but the check box does not retain it's value when switching to a different screen and back.

And while I'm being demanding (sorry), would it be difficult to add a sort option on the Library for date the series was added to History?

**Comment by Elwador** [comment]
the custom calendar is not the same as the Simulcast Calendar from CR - for the custom calendar i look at the recently released episodes
i think the lang dropdown has no impact what so ever on the custom calendar 
i removed all the "dub" releases because some episodes were listed like 5 times with the different dubs
and i can save the state of the checkbox if the custom calendar is selected

np, i could add something for that to the history but all series that are already added will have the date of the next refresh when i add it because currently there is no add date saved

i absolutly expect bugs with the new calendar and search 😅

**Comment by petenun** [comment]
I totally get the problem with the multiple dub releases. I've never been happy with the way that CR handles the dub languages it's both noisy and vague at the same time. Heck, even on their own site, they treat Dub like a binary value (True or False) even though there are multiple values based on the language. In MY perfect world, it would be nice to only see English dubs, but if Crunchyroll can't even do it, then it's probably an unrealistic ask. 😂

Thank you for looking into the checkbox persistence and the added date. I think both of those will be handy. And the search feature is an awesome addition! 🎉

**Comment by Elwador** [comment]
i think with the new release this issue should be pretty much done if there are any issues just make a new one

**Comment by petenun** [comment]
It's looking beautiful, and the dub filter looks promising. Thanks for all the effort you put into this!
