### ISSUE TITLE
What kind of control is this?

### ISSUE THREAD

**Issue by Askadelion** [Crunchy-DL/Crunchy-Downloader#3]
![CRD_Mwh5pcTv7W](https://github.com/Crunchy-DL/Crunchy-Downloader/assets/41443013/7fa2fc60-4a52-4d43-bbc1-e4bd6d16f239)

I would be interested to know which control this is, I have been looking for something similar for a while?

**Comment by Elwador** [comment]
i am using Avalonia Ui for the ui and on the settings page i used the "SettingsExpander" control for the different options

**Comment by Askadelion** [comment]
Thanks, very nice of you to answer me.
