### ISSUE TITLE
Custom Calendar dub filtering not 100% accurate (v 1.5.1)

### ISSUE THREAD

**Issue by petenun** [Crunchy-DL/Crunchy-Downloader#33]
I'm sure you're getting tired of hearing from me. 😅

I noticed that the results shown in the custom calendar do not perfectly match the results in the non-custom calendar. The episodes don't show up in the custom calendar either with or without dub filtering. Hopefully it's just needing a simple algorithm tweak for the custom calendar.

Here's what I see in the custom calendar filtered for English dubs:
![image](https://github.com/user-attachments/assets/163750a6-4991-4fe9-9617-9776a77cc32f)

And here's the standard unfiltered calendar. These two english dubs are missing from the custom calendar
![image](https://github.com/user-attachments/assets/dfb1afe3-2338-4cf6-b3b9-58b0e9e56e0e)

**Comment by Elwador** [comment]
i guess that is because i filtered the episodes in the custom calendar to only show new releases so if an episodes has been released weeks/months or years ago and gets an dub now it's not shown 

but i can just add a toggle for that

**Comment by Vorffeed** [comment]
Sorry to say but apparently the new update has loaded the hide dubs of the calendar, if I restart or update the calendar it deactivates it, without being marked as it happened before.

**Comment by Elwador** [comment]
should be fixed again copy paste error 😅

**Comment by petenun** [comment]
Just checked out the new release over morning coffee and it's looking great. I'm seeing all expected episodes now. Thanks again!
