### ISSUE TITLE
cant find cdm files in widevine folder

### ISSUE THREAD

**Issue by KAK232** [Crunchy-DL/Crunchy-Downloader#34]
cant find cdm files in widevine folder ?

**Comment by petenun** [comment]
How are your files named? Mine looks like this:

![image](https://github.com/user-attachments/assets/841c1266-ea9d-41b9-9fd6-b4800187df04)

**Comment by petenun** [comment]
Maybe you can re-state the question. Are you putting your CDM files in the widevine directory and the program is not finding them? You do realize that you need to create and provide your own L3 CDM files, right?

**Comment by KAK232** [comment]
@petenun provide your own L3 CDM files?

**Comment by petenun** [comment]
I just wrote a post, which I hope will answer your questions.

https://github.com/Crunchy-DL/Crunchy-Downloader/discussions/36

**Comment by sergiohzph** [comment]
You need to rip your own L3 CDM, and it's something we can't help you about, do your own research and you'll find how to extract those files.
