### ISSUE TITLE
Multi-Audio Download

### ISSUE THREAD

**Issue by Nonobis** [Crunchy-DL/Crunchy-Downloader#4]
Could you allow for multi audio download like for the subs ?

**Comment by Elwador** [comment]
into the same file? because as far as i know not all languages have the same video so it may not match

**Comment by Elwador** [comment]
i added it to [v1.4.6](https://github.com/Crunchy-DL/Crunchy-Downloader/releases/tag/v1.4.6) but didn't have much time to test it 
if something isn't working correctly please tell me and i will fix it tomorrow

**Comment by Nonobis** [comment]
Thnaks i will test it

**Comment by Nonobis** [comment]
it's partially working, i cant select jp & en (perfect).
But download is not working.
If i take a anime with dub jp & eng, i got this error "No video data found"

https://www.crunchyroll.com/fr/series/GKEH2G9XV/mobile-suit-gundam

**Comment by Elwador** [comment]
"No Video Data Found" usually happens when you try to download a premium episode without having premium

**Comment by Nonobis** [comment]
for now i a a 7 days trial premium account

**Comment by Elwador** [comment]
i just tried S01E01 with en-US,ja-JP dub selection and it worked 

maybe it is because of the trial account - i will test that in the evening

**Comment by Elwador** [comment]
ok i just tried it with a trial account and could download all episodes without a problem

maybe try to logout and login again in the downloader - or post a screenshot of your settings that i can check that

**Comment by KAK232** [comment]
Do not withdraw all translations
![Screenshot 2024-05-29 at 13-01-45 Watch Anime de Training! EX](https://github.com/Crunchy-DL/Crunchy-Downloader/assets/169140265/140e302e-7955-4bf5-817c-a63314429f34)

![لقطة شاشة 2024-05-29 130353](https://github.com/Crunchy-DL/Crunchy-Downloader/assets/169140265/c0faff4e-f2bd-4e19-af84-2dd165389a66)

https://www.crunchyroll.com/fr/series/GRE5KZQN6/anime-de-training-ex

**Comment by Elwador** [comment]
@KAK232 maybe start a new issue and explain exactly what it is you want to achieve. If you don't want to download all subtitles change it in the settings and if it is about not including "العربية" i can look into that
