### ISSUE TITLE
Custom Calendar Current Day Download Link Not Clickable

### ISSUE THREAD

**Issue by petenun** [Crunchy-DL/Crunchy-Downloader#41]
I don't know if this is expected behavior or not, but when viewing the custom calendar, the current day's Download link for any given episode is not active / not clickable, whereas all previous days' links are active and clickable.  This behavior does not seem to match that of the standard (not custom) calendar. 

![image](https://github.com/user-attachments/assets/d7eddea4-7eb3-4beb-9ea7-5d86a398ba89)

**Comment by Elwador** [comment]
has the time already passed? the 8:59 AM

**Comment by petenun** [comment]
Sorry to waste your time. This was a stupid user problem. 😬

**Comment by Elwador** [comment]
no worries
