### ISSUE TITLE
Error download video

### ISSUE THREAD

**Issue by vabarboza** [Crunchy-DL/Crunchy-Downloader#43]
I'm having trouble downloading videos with forced subtitles in PT-BR, if I uncheck the HRDSUB option the download is complete, if I leave it selected the PT-BR option generates the image error
![Captura de Tela (2)](https://github.com/user-attachments/assets/34075725-eb7d-4f2f-b119-53536aad9bbb)

**Comment by Elwador** [comment]
hardsub != forced subtitles 
check the wiki - https://github.com/Crunchy-DL/Crunchy-Downloader/wiki/5-%E2%80%90-Settings#softsubs-language

**Comment by vabarboza** [comment]
Really, thank you very much
