### ISSUE TITLE
 Video corrupted in MP4 file only

### ISSUE THREAD

**Issue by Tesseractxss** [Crunchy-DL/Crunchy-Downloader#45]
Hello, I noticed that the video gets corrupted if it is in MP4.

The video plays normally only if you change the audio track to Japanese audio, but it does not work if you change it to any other language. And this only happens in the MP4 file, in the mkv file, everything works normally.

I downloaded several different videos, and the same thing happens in all of them, whenever the file is MP4.

I'm using v1.5.7

**Comment by Vorffeed** [comment]
Let's see, if you say that the video looks fine if you don't change the audio track, but it gets corrupted when you change the audio track, it's not a question of the programme, but of how you have the codecs configured in your player. 😅

**Comment by Elwador** [comment]
In this case, it was a problem with the program, particularly with the MP4 option and sync timings option. The FFmpeg command was incorrect. It should work now in the new release [v1.5.8](https://github.com/Crunchy-DL/Crunchy-Downloader/releases/tag/v1.5.8)
