### ISSUE TITLE
Login does not work

### ISSUE THREAD

**Issue by lessyy** [Crunchy-DL/Crunchy-Downloader#47]
I have a premium account , But when I log in it says invalid account，I also created L3

![20240725152624](https://github.com/user-attachments/assets/44bdd831-2594-42d6-b68b-9b0ecc88571f)
![20240725152638](https://github.com/user-attachments/assets/f8399da5-cdce-4ac3-8b51-2dcab1db4aab)

**Comment by lessyy** [comment]
![20240725152654](https://github.com/user-attachments/assets/65b8728f-dfd2-40bb-88b4-f74e63ed47f9)

**Comment by Elwador** [comment]
to see why it not works i would need a response for a certain request - either i send you a special build for that on discord or you check https://www.crunchyroll.com/account/membership -> press f12 -> go to the network tab -> maybe you have the refresh here to see something -> input this into the filter "subs/v3/subscriptions" and you should remain with one entry - i need the response from this entry 
chrome would look like this:
![image](https://github.com/user-attachments/assets/b33668e7-c983-444e-bee7-bf84930caed5)
maybe remove "ctp_account_id", "account_id" and "__href__" if you poste it here

**Comment by lessyy** [comment]
Here is the log file:
[logfile.txt](https://github.com/user-attachments/files/16385474/logfile.txt)

**Comment by lessyy** [comment]
"subs/v3/subscriptions" is not responding
![20240726092815](https://github.com/user-attachments/assets/8a296953-0213-462d-93f7-40c5cdd262e1)

**Comment by Elwador** [comment]
that contains like nothing 😆 did you enable the log and went to the login page maybe even logout and log back in 

don't go to the ""subs/v3/subscriptions" is not responding" crunychroll itselfe should make the request to that page when you go to the https://www.crunchyroll.com/account/membership and are logged in

**Comment by lessyy** [comment]
"subs/v3/subscriptions" is this？😢

    "__class__": "v3_subscription",
    "__href__": "/subs/v3/subscriptions/b4bb6b94-6208-578a-9a0f-4415c2748541",
    "__links__": null,
    "__actions__": null,
    "account_id": 1071193185,
    "ctp_account_id": "b4bb6b94-6208-578a-9a0f-4415c2748541",
    "cycle_duration": "P1M",
    "next_renewal_date": "2022-10-03T11:22:26Z",
    "currency_code": "",
    "is_active": false,
    "tax_included": false,
    "subscription_products": [],
    "future_subscription_change": null,
    "third_party_subscription_products": [
        {
            "effective_date": "2023-08-22T03:11:42Z",
            "source": "itunes",
            "source_reference": "530001167899671",
            "sku": "cr.ios.fanpack.monthly",
            "tier": "fan_pack",
            "active_free_trial": false,
            "in_grace": true,
            "on_hold": false,
            "auto_renew": true,
            "in_grace_expiration_date": "2024-08-07T04:59:48Z",
            "expiration_date": "2024-07-22T04:59:48Z"
        }
    ],
    "nonrecurring_subscription_products": [],
    "funimation_subscriptions": []
}



And Here is the log file:
[
[Uploading logfile.txt…]()
](url)

**Comment by Elwador** [comment]
yes that was what i needed - i copied the stuff and removed it so that your account id stays private

**Comment by lessyy** [comment]
> 是的，这就是我需要的 - 我复制了内容并将其删除，以便您的帐户 ID 保持私密

thanks

**Comment by Elwador** [comment]
should be fixed with [v1.5.10](https://github.com/Crunchy-DL/Crunchy-Downloader/releases/tag/v1.5.10)
