### ISSUE TITLE
Downloader Crash Downloading Specific Episode

### ISSUE THREAD

**Issue by BartiBartosz** [Crunchy-DL/Crunchy-Downloader#48]
The program crashes while downloading EP9 from MyDress-Up Darling. All other episodes downloaded without any problems.

Tried different settings, buit the program still crashes.

**Comment by Elwador** [comment]
i will look into a fix for the next release - for now if you want to download the episode disable the chapters

**Comment by BartiBartosz** [comment]
Works for me. Thx for the info
