### ISSUE TITLE
error when downloading a large Crunchyroll episode

### ISSUE THREAD

**Issue by dreezy-official** [Crunchy-DL/Crunchy-Downloader#50]
When I try to download a long episode of Demon Slayer it only ends up downloading the subtitles.

https://www.crunchyroll.com/pt-pt/watch/GX9UQE82J/the-hashira-unite

![2024-07-27_22-15-21](https://github.com/user-attachments/assets/4e5fa50b-2352-4659-b085-b0827f3ac3a4)

**Comment by R4H4T069** [comment]
hello bro can you tell me how can i get cdm keys

**Comment by dreezy-official** [comment]
> hello bro can you tell me how can i get cdm keys

I saw the tutorial in an article Crunchyroll Downloader which was probably removed because it was illegal in . 
original link: https://github.com/OpenSTDL/CrunchyDL/discussions/23

ex:
![2024-07-28_11-59-54](https://github.com/user-attachments/assets/b767a16f-94fa-410d-aac2-1eedd237608e)


but here you have it, I used the one from the first link:
https://forum.videohelp.com/threads/408031-Dumping-Your-own-L3-CDM-with-Android-Studio
https://github.com/wvdumper/dumper

**Comment by dreezy-official** [comment]
> hello bro can you tell me how can i get cdm keys

I can't, as you can see, I tried to explain it to you but the post was removed.

**Comment by Elwador** [comment]
> When I try to download a long episode of Demon Slayer it only ends up downloading the subtitles.
> 
> https://www.crunchyroll.com/pt-pt/watch/GX9UQE82J/the-hashira-unite
> 
> ![2024-07-27_22-15-21](https://private-user-images.githubusercontent.com/75680397/352777565-4e5fa50b-2352-4659-b085-b0827f3ac3a4.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNjU3NjksIm5iZiI6MTcyMjE2NTQ2OSwicGF0aCI6Ii83NTY4MDM5Ny8zNTI3Nzc1NjUtNGU1ZmE1MGItMjM1Mi00NjU5LWIwODUtYjA4MjdmM2FjM2E0LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDExMTc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0Mjk3N2MwZmFiMDI3ZjdkZGYwZTljMTE4M2YwZWVkMDNmYTg4NjNhNWFiYjQyNTA0MzY1ZmI2NmI0OTA1YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qS46UZ6W3gqMLPh7kq2fh3S2pY0tV960aKyx9WtdyqM)

i have no problem downloading the episode with the same dub/sub settings - so the problem most likely is on your end 
make sure your settings are correct and maybe turn on log mode to see if there are any errors

**Comment by dreezy-official** [comment]
> > When I try to download a long episode of Demon Slayer it only ends up downloading the subtitles.
> > https://www.crunchyroll.com/pt-pt/watch/GX9UQE82J/the-hashira-unite
> > ![2024-07-27_22-15-21](https://private-user-images.githubusercontent.com/75680397/352777565-4e5fa50b-2352-4659-b085-b0827f3ac3a4.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNjU3NjksIm5iZiI6MTcyMjE2NTQ2OSwicGF0aCI6Ii83NTY4MDM5Ny8zNTI3Nzc1NjUtNGU1ZmE1MGItMjM1Mi00NjU5LWIwODUtYjA4MjdmM2FjM2E0LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDExMTc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0Mjk3N2MwZmFiMDI3ZjdkZGYwZTljMTE4M2YwZWVkMDNmYTg4NjNhNWFiYjQyNTA0MzY1ZmI2NmI0OTA1YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qS46UZ6W3gqMLPh7kq2fh3S2pY0tV960aKyx9WtdyqM)
> 
> i have no problem downloading the episode with the same dub/sub settings - so the problem most likely is on your end make sure your settings are correct and maybe turn on log mode to see if there are any errors

https://github.com/user-attachments/assets/a5224195-d790-48ce-b357-da37df1f4f0d

Even with Log Mode it continues to give problems and I don't know what it could be, I'll try to install a clean installation and see if it could be some configuration...

**Comment by Elwador** [comment]
did you change anything in the muxing settings?

**Comment by dreezy-official** [comment]
> did you change anything in the muxing settings?

yes only, the first 4 options.
![2024-07-28_15-45-44](https://github.com/user-attachments/assets/d9e35410-a292-4c7a-8983-ad4adf01d830)

**Comment by Elwador** [comment]
most likely a problem with the mp4 option

**Comment by dreezy-official** [comment]
> most likely a problem with the mp4 option

I can post the logfile later if necessary to analyze what it could be.

**Comment by dreezy-official** [comment]
**logfile.txt:**
```
Log mode enabled.
[ffmpeg] Merging failed with exit code -12

```
https://github.com/user-attachments/assets/6f8d4325-128c-4819-9e32-f1af1e944bde

**Comment by Elwador** [comment]
if you disable chapters it should work

**Comment by dreezy-official** [comment]
> if you disable chapters it should work

I will test thanks.
