### ISSUE TITLE
Add Hardcoded subtitles [Feature]

### ISSUE THREAD

**Issue by Superetie** [Crunchy-DL/Crunchy-Downloader#54]
Can you please add Hardcoded subtitle support? If I download an anime with German dub, without subs, Japanese texts should normally still be translated but this program can't do that yet, please add this function

**Comment by Elwador** [comment]
https://github.com/Crunchy-DL/Crunchy-Downloader/wiki

**Comment by Superetie** [comment]
I've already looked through everything there and couldn't find anything about it.

**Comment by Superetie** [comment]
> https://github.com/Crunchy-DL/Crunchy-Downloader/wiki

I've already looked through everything there and couldn't find anything about it.

**Comment by Elwador** [comment]
set the settings to download ger dub and ger soft sub and select the include signs option of the soft subs

**Comment by Superetie** [comment]
> set the settings to download ger dub and ger soft sub and select the include signs option of the soft subs

Thank you very much, it works
