### ISSUE TITLE
Downloaded Video is not saving in that folder

### ISSUE THREAD

**Issue by naniworks124** [Crunchy-DL/Crunchy-Downloader#6]
Hi bro Premium Downloaded Videos Are Not Saving In Videos Folder when The Download Is finished please tell me any solution for this.
![Screenshot_28](https://github.com/Crunchy-DL/Crunchy-Downloader/assets/131702112/3fabdeaf-a55f-4d58-ad52-e7d7cafc4a58)
![Screenshot_78](https://github.com/Crunchy-DL/Crunchy-Downloader/assets/131702112/30398f16-a642-4887-b9f4-f7465e817426)

**Comment by naniworks124** [comment]
It's working only for Japanese + English but not working for Other Languages.

**Comment by Elwador** [comment]
can you try it with [v1.4.14](https://github.com/Crunchy-DL/Crunchy-Downloader/releases/tag/v1.4.14) and tell me if it works  - for me it just got stuck on muxing with that many languages but hopefully it also fixes the problem you had
![image](https://github.com/Crunchy-DL/Crunchy-Downloader/assets/75888166/761d6f32-11ae-4100-ba24-fada2dd907cb)

**Comment by naniworks124** [comment]
I just downloaded the new Version but **same Problem it's not MUXING after downloading of Audios It's Saying Done** but not available in videos folder
![Screenshot_79](https://github.com/Crunchy-DL/Crunchy-Downloader/assets/131702112/f0c784cf-7f7c-413b-b9cb-6e2202bc3c4a)

**Comment by Elwador** [comment]
the new version [(v1.4.15)](https://github.com/Crunchy-DL/Crunchy-Downloader/releases/tag/v1.4.15) should now finally fix this - i tried it with the same languages you have selected

**Comment by naniworks124** [comment]
**ISSUE SOLVED** Thank you So much for responding faster and fixing the issue bro. you're the best 😍
