### ISSUE TITLE
[Multiple features] A way to set a desired language for the episode titles | temp folder

### ISSUE THREAD

**Issue by LorenorZorro3000** [Crunchy-DL/Crunchy-Downloader#62]
I have a few suggestions.

1. A way to set a desired language for the episode titles.
2. The option to specify a temp folder where the files are downloaded and processed. After that, the data is moved to the specified download folder.

Thank you very much in advance. Best regards, LorenorZorro3000

**Comment by Elwador** [comment]
1 - just change the history lang for that
2 - will probably not add that
