### ISSUE TITLE
[Feature] Any solution with series that only have a single audio?

### ISSUE THREAD

**Issue by Vorffeed** [Crunchy-DL/Crunchy-Downloader#66]
Let's see how I explain this.
I have configured the programme to download everything in Japanese with Spanish subtitles, but there are series that only have audio in Chinese or Korean.
And of course, in the calendar you see those series because they are in your region, but when you download them they give an error because of the language configuration.
You could implement an option that if the added chapter does not have the desired language look at another option that says alternative language order and select which languages you want to download if you do not find them, ie if the Japanese does not exist verify that the Chinese exists and download only that and if the Chinese does not exist but the Korean if it exists only download that.
Because by default I only download the original language, with the video and subtitles, and if I select those three audio languages in options I would do it in all the series, but the multi-language option is not what I am looking for because then I would download it in all the series that have those languages and that is not what I want.

**Comment by Elwador** [comment]
you could/should use the override language from the history tab for that

**Comment by Vorffeed** [comment]
It tells me the same thing
![image](https://github.com/user-attachments/assets/b0ff0931-6a94-4ece-92ba-c4707fb0eb50)

**Comment by Elwador** [comment]
i can't help you with more context of what you did - if you set the override dub correctly this message wouldn't appear

**Comment by Vorffeed** [comment]
> you could/should use the override language from the history tab for that

I don't think I understood you when you said this, because I went to history and from there I selected the episode and I got the message above.

![image](https://github.com/user-attachments/assets/38fbc9e6-5de8-4fd9-8c17-0055d1be6021)

If I select several languages, Japanese, Chinese and Korean, it picks them up, but that's not what I'm interested in, because I don't want to have several dubs if it turns out to be those three, as in the screenshot where the episode has not only Japanese but also Chinese.
![image](https://github.com/user-attachments/assets/38fbc9e6-5de8-4fd9-8c17-0055d1be6021)

**Comment by Elwador** [comment]
i am talking about what was original discussed here:
https://github.com/Crunchy-DL/Crunchy-Downloader/discussions/35

and also came up here:
https://github.com/Crunchy-DL/Crunchy-Downloader/discussions/49

and can also be found in the wiki:
https://github.com/Crunchy-DL/Crunchy-Downloader/wiki/4-%E2%80%90-Download-History

**Comment by Vorffeed** [comment]
Wtf... I've hit edit ahi a few times thinking it was for another company. 😱
Thanks 👍

**Comment by Vorffeed** [comment]
I've been trying, and it already makes me the audios of the series that do not have Japanese dubbing, I get the Chinese or Korean by default, but when I go to edit another one that does not bring sub in Castilian because the bastards announced that it was global license at the end the Castilian decided that it did not enter in the license.

![image](https://github.com/user-attachments/assets/46e9a5fc-44cb-4c8b-bb34-0ef4354043cb)

So I configured it as you can see in the image because I always had to change the calendar in es-419 to download with the latin subtitle, but here it still respects the original schedule and says that it doesn't download the latin subtitle because in the configuration it's set to spanish and it downloads it without sub ><

![image](https://github.com/user-attachments/assets/71637bf8-7791-4669-9598-1b8fc888aa4d)

**Comment by Elwador** [comment]
if there is no es-419 subtitle the downloader can't download it nothing i can do

**Comment by Vorffeed** [comment]
Yes, there are, but the dubbing and subtitle override is not picked up from the history.

![image](https://github.com/user-attachments/assets/939cdfd8-8aba-4957-85a9-d7c7e5755887)

However, if you change it from the configuration itself, it does pick it up.

![image](https://github.com/user-attachments/assets/2a99cee4-4392-4784-8e19-16f6317ce28e)

![image](https://github.com/user-attachments/assets/76721a9d-994c-4a4a-b099-09cfca01d77e)

**Comment by Elwador** [comment]
should be working again in [v1.5.15](https://github.com/Crunchy-DL/Crunchy-Downloader/releases/tag/v1.5.15)

**Comment by Vorffeed** [comment]
Thank you, it's working 👍🏆
