### ISSUE TITLE
Can't find cdm files inwidewine folder

### ISSUE THREAD

**Issue by naniworks124** [Crunchy-DL/Crunchy-Downloader#7]

**Comment by Elwador** [comment]
crunchyroll updated and it's not possible anymore to download non drm protected streams - [see end of readme](https://github.com/Crunchy-DL/Crunchy-Downloader/blob/master/README.md)

**Comment by naniworks124** [comment]
bro can you tell me how to that widewine thing really i don't know about that

**Comment by naniworks124** [comment]
please i am newbie in this

**Comment by Elwador** [comment]
just google how to dump l3 cdm with android studio and you should find some guides

**Comment by naniworks124** [comment]
I have done all the steps bro but when downloading audio it's the application keeps closing

**Comment by Elwador** [comment]
if you enable the log mode in the settings do you get errors in the log file?

**Comment by naniworks124** [comment]
I have done Even in Logfile it's showing only Log mode enabled.

**Comment by naniworks124** [comment]
@Elwador please look into this

**Comment by Elwador** [comment]
can you check the new version if it shows you more in the log file?

**Comment by naniworks124** [comment]
Here it is Still stopping
Can i have your telegram id to tell you more please.

Below i attached log file kindly check
[logfile.txt](https://github.com/user-attachments/files/15900193/logfile.txt)

**Comment by Elwador** [comment]
in version v1.4.20 i added even more log messages - because even if i set stuff intentionally to a wrong value i don't get it to crash...
and do you have discord? it would be a lot easier and faster to debug that with you there

**Comment by naniworks124** [comment]
This Is my Discored Id bro : **nanijack** please solve my issue

Thank you for all your resposes

**Comment by Elwador** [comment]
sent you a friend request - but you could also just join the discord server https://discord.gg/zDKNU8UUqt
