### ISSUE TITLE
[Bug]  Closed Captions subtitle file empty

### ISSUE THREAD

**Issue by The-Math-God** [Crunchy-DL/Crunchy-Downloader#72]
hi i tried to download an anime with "include closed captions" enabled 
but when i download it all i get is a empty .ass file
and i know for a fact this anime has closed captions
i've included the logfile as well as one of the .ass files

[logfile.txt](https://github.com/user-attachments/files/16575545/logfile.txt)

[Gankutsuou - S01E01 [1080p].02.eng.CC.txt](https://github.com/user-attachments/files/16575546/Gankutsuou.-.S01E01.1080p.02.eng.CC.txt)

**Comment by Elwador** [comment]
should be working again in [v1.5.15](https://github.com/Crunchy-DL/Crunchy-Downloader/releases/tag/v1.5.15)
