### ISSUE TITLE
[Bug] ffmpeg consistently fails on some videos with exit code -22, issue with Include Episode Description setting

### ISSUE THREAD

**Issue by eepyfemboi** [Crunchy-DL/Crunchy-Downloader#73]
Theres several episodes which ffmpeg consistently fails to convert, one of such is [The Slime Diaries E7 English Dub](https://www.crunchyroll.com/watch/G4VUQ9KQN/here-comes-the-demon-lord)
After a bit of research I found that the "Include Episode Description" setting was the cause, as disabling it allowed ffmpeg to work without any issues
I would figure out the problem myself and put in a PR, but I'm too busy with other projects at the moment.

**Comment by Elwador** [comment]
no worries i will look into it - i am more surprised that alot of people seem to use the mp4 option but why? ^^

**Comment by eepyfemboi** [comment]
it's probably because it's more familiar, or it could be for compatibility ¯\_(ツ)_/¯
