### ISSUE TITLE
[Bug] Subscription experation check doesn't account for UTC time

### ISSUE THREAD

**Issue by BattouKen** [Crunchy-DL/Crunchy-Downloader#74]
Me ha salido todo el día esto, y se supone mi premium dura hasta 40min más, de hecho en la web salgo como premium.

Edit: removed images since they show your CR username

`"expiration_date": "2024-08-13T21:19:33Z",
      "in_grace_expiration_date": "0001-01-01T00:00:00"`

antes del día de hoy podía descargar perfectamente. (descargue con otro downloader recién y me deja perfectamente =/

**Comment by Elwador** [comment]
it appears that CR is using utc times but i still compare it like it is no UTC time so depending on how many hours you are behind / before utc subscription check might not work correctly

it should work again after a few hours or your subscription got renewed

i will fix it in the next release

**Comment by BattouKen** [comment]
> it appears that CR is using utc times but i still compare it like it is no UTC time so depending on how many hours you are behind / before utc subscription check might not work correctly
> 
> it should work again after a few hours or your subscription got renewed
> 
> i will fix it in the next release

la cosa es que con otro downloader (que ya no tiene soporte) me descargo sin problemas. Estaré a la espera del parche 👍💯

![image](https://github.com/user-attachments/assets/537f5d38-1b0f-4f55-9dea-6ca6de465d06)

**Comment by Elwador** [comment]
it probably works again before i release the update ^^

**Comment by Elwador** [comment]
should be fixed now for the future when a subscription approaches the end
