### ISSUE TITLE
Video quality

### ISSUE THREAD

**Issue by nigoki2** [Crunchy-DL/Crunchy-Downloader#8]
Hi.
First of all, thank you for your work!
This is my problem: the video quality is set to 720 but the download result always gives me a 1080 video.
Did I make something wrong ?
Thank you again.

**Comment by naniworks124** [comment]
Bro where do you got widevine files for me This app keeps stopping

**Comment by Elwador** [comment]
@nigoki2 i had a typo in the check in the new version it should work as intended

**Comment by nigoki2** [comment]
@Elwador You rules! It works fine!
One last question: is it possible to set ScaledBorderAndShadow: no into subtitles ?

**Comment by Elwador** [comment]
do you want "ScaledBorderAndShadow" removed completly or only set to no?

**Comment by nigoki2** [comment]
Well, that could become an option, so my answer would be set to no.

**Comment by Elwador** [comment]
new version now has this:
![image](https://github.com/Crunchy-DL/Crunchy-Downloader/assets/75888166/b3068831-625c-4711-b2ae-14c8a837bddb)

**Comment by nigoki2** [comment]
Thank you very much Elwador!

**Comment by naniworks124** [comment]
@nigoki2 Bro can you tell me or share me how can i get private key and client id
