### ISSUE TITLE
[Bug] error aislado. No descarga y aun figuro como premium en la web.

### ISSUE THREAD

**Issue by BattouKen** [Crunchy-DL/Crunchy-Downloader#80]
bueno este problema seria un "bug" aislado supongo, ya que sucede que estoy en el día 31 de mi suscripción premium y aun tengo acceso a seguir viendo anime desde la web, pero el downloader no me deja descargarlos porque tal vez me sigue detectando sin suscripción ya que aun no se a renovado el pago persistente del premium:

![image](https://github.com/user-attachments/assets/45633846-db1a-4761-ab48-e8896a7765a9)

Edit: removed image to make sure it doesn't show cr user name

comentar eso sí, que anoche como las primeras horas si me dejaba aun sin actualizar, eso si probablemente porque aún no terminaban el ultimo día de sub premium. Espero tenga solución. 👍💯

**Comment by Elwador** [comment]
without knowing what you get in the log i can't say if it is a bug or if crunchyroll is being stupid

**Comment by BattouKen** [comment]
> without knowing what you get in the log i can't say if it is a bug or if crunchyroll is being stupid
> 
> also what does it show on https://www.crunchyroll.com/account/membership

![image](https://github.com/user-attachments/assets/cd9a6b69-6e4b-4d2e-93c9-d7c28ea7107f)

![image](https://github.com/user-attachments/assets/0a4f6a04-5daf-4c22-82f6-11c4b5622b13)

**Comment by BattouKen** [comment]
según yo debería dejar descargar ya que aún me deja ver anime en la web no?

**Comment by Elwador** [comment]
it should let you download but the question is what crunchyroll returns if i ask them if you have a subscription - check this https://github.com/Crunchy-DL/Crunchy-Downloader/issues/47#issuecomment-2251033016 where i described how to get the info

should look something like this:
```json
    "__class__": "v3_subscription",
    "__href__": "",
    "__links__": null,
    "__actions__": null,
    "account_id": ,
    "ctp_account_id": "",
    "cycle_duration": "",
    "next_renewal_date": "0001-01-01T00:00:00Z",
    "currency_code": "",
    "is_active": false,
    "tax_included": false,
    "subscription_products": [],
    "future_subscription_change": null,
    "third_party_subscription_products": [{
            "effective_date": "2024-06-19T16:36:41Z",
            "source": "google-play",
            "source_reference": "d",
            "sku": "crunchyroll.google.premium.monthly",
            "tier": "premium",
            "active_free_trial": true,
            "in_grace": false,
            "on_hold": false,
            "auto_renew": true,
            "expiration_date": "2024-06-26T16:34:11Z"
        }
    ],
    "nonrecurring_subscription_products": [],
    "funimation_subscriptions": []
```

**Comment by BattouKen** [comment]
[logfile.txt](https://github.com/user-attachments/files/16633040/logfile.txt)

`Log mode enabled.
Log mode enabled.
{
  "account_id": 17482651,
  "ctp_account_id": "21dca12b-79c3-5842-9de2-beec690a68a5",
  "cycle_duration": "P1M",
  "next_renewal_date": "2024-08-15T17:19:38-04:00",
  "currency_code": "",
  "is_active": false,
  "tax_included": false,
  "subscription_products": [],
  "third_party_subscription_products": [
    {
      "effective_date": "2024-07-13T17:23:47-04:00",
      "Source": "google-play",
      "source_reference": "pnmgmmahahogmjdbcaancpno.AO-J1OyFB9eNnf-P_maNmhGWZoqGH81QuPBILqmVe6NSLcTRO9gaKWlu147EE8VfdU0IVfWgUSeo03EyqxqhcqM93BWZQkA7f0ZYIL-5KUAVoM3qntuTCVQ",
      "Sku": "crunchyroll.google.fanpack.monthly",
      "Tier": "fan_pack",
      "active_free_trial": false,
      "in_grace": true,
      "on_hold": false,
      "auto_renew": true,
      "expiration_date": "0001-01-01T00:00:00",
      "in_grace_expiration_date": "2024-08-15T17:19:38-04:00"
    }
  ],
  "nonrecurring_subscription_products": [],
  "funimation_subscriptions": []
}`

**Comment by BattouKen** [comment]
![image](https://github.com/user-attachments/assets/b1d69975-0265-4635-8970-0e855cdfe90a)

![image](https://github.com/user-attachments/assets/1238da23-bdfc-44c1-b572-7e88fc43a241)

![image](https://github.com/user-attachments/assets/1e6a688a-e6f3-44e7-a5c9-8b5110ee3280)

**Comment by Elwador** [comment]
ok so crunchyroll is being stupid because both dates that are relevant are in the past

which means according to crunchyroll your subscription has ended

"next_renewal_date": "2024-08-15T17:19:38-04:00",
"in_grace_expiration_date": "2024-08-15T17:19:38-04:00"

also you don't have to send images from the other downloader working because it most likely doesn't check the subscription with the date so that is why it's working

**Comment by BattouKen** [comment]
> ok so crunchyroll is being stupid because both dates that are relevant are in the past
> 
> which means according to crunchyroll your subscription has ended
> 
> "next_renewal_date": "2024-08-15T17:19:38-04:00", "in_grace_expiration_date": "2024-08-15T17:19:38-04:00"
> 
> also you don't have to send images from the other downloader working because it most likely doesn't check the subscription with the date so that is why it's working

vale gracias por la aclaración.

**Comment by Elwador** [comment]
try it with the new version [v1.5.19](https://github.com/Crunchy-DL/Crunchy-Downloader/releases/tag/v1.5.19)

**Comment by BattouKen** [comment]
> try it with the new version [v1.5.19](https://github.com/Crunchy-DL/Crunchy-Downloader/releases/tag/v1.5.19)

cool ty

![image](https://github.com/user-attachments/assets/4002f926-1870-4cdc-80a3-fe3147c4d2dd)

**Comment by BattouKen** [comment]
oh! recién me fije y el .xml de los chapters se queda fuera del .mkv

![image](https://github.com/user-attachments/assets/e7e771d9-fd6f-4eb4-a719-e9c8c5a6fa63)

**Comment by Elwador** [comment]
create a new issue with an explanation what you did so that i can try to reproduce it
