### ISSUE TITLE
[Bug] Doesn't download English CC 

### ISSUE THREAD

**Issue by 21R01A7263** [Crunchy-DL/Crunchy-Downloader#81]
In theory, the downloader should've downloaded the Closed Captions for My Hero Academia episode 148

![image](https://github.com/user-attachments/assets/af10d7b5-8a31-4916-89b0-cd33387aa9eb)

In the output however, no subtitles are downloaded

![image](https://github.com/user-attachments/assets/7bde13c4-796c-4644-be97-f54bd281e16a)

The state of the downloader is

![image](https://github.com/user-attachments/assets/2d57edce-c626-4f40-9ca1-92ec87f072f2)

**Comment by Elwador** [comment]
have you enabled CC download in the settings?

**Comment by 21R01A7263** [comment]
ah, that fixed it. shouldn't it be enabled by default tho??

**Comment by Elwador** [comment]
no

**Comment by 21R01A7263** [comment]
alright, i will be closing this now.
