### ISSUE TITLE
[Bug] Calendar not working

### ISSUE THREAD

**Issue by rifatozkancomtr** [Crunchy-DL/Crunchy-Downloader#84]
Log mode enabled.

Error: System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at CRD.Utils.HttpClientReq.SendHttpRequest(HttpRequestMessage request) 
 Response: <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131}button,html{font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji}@media (prefers-color-scheme:dark){body{background-color:#222;color:#d9d9d9}body a{color:#fff}body a:hover{color:#ee730a;text-decoration:underline}body .lds-ring div{border-color:#999 transparent transparent}body .font-red{color:#b20f03}body .pow-button{background-color:#4693ff;color:#1d1d1d}body #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}body #challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+)}}body{display:flex;flex-direction:column;min-height:100vh}body.no-js .loading-spinner{visibility:hidden}body.no-js .challenge-running{display:none}body.dark{background-color:#222;color:#d9d9d9}body.dark a{color:#fff}body.dark a:hover{color:#ee730a;text-decoration:underline}body.dark .lds-ring div{border-color:#999 transparent transparent}body.dark .font-red{color:#b20f03}body.dark .pow-button{background-color:#4693ff;color:#1d1d1d}body.dark #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}body.dark #challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+)}body.light{background-color:transparent;color:#313131}body.light a{color:#0051c3}body.light a:hover{color:#ee730a;text-decoration:underline}body.light .lds-ring div{border-color:#595959 transparent transparent}body.light .font-red{color:#fc574a}body.light .pow-button{background-color:#003681;border-color:#003681;color:#fff}body.light #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}body.light #challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI2ZjNTc0YSIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjZmM1NzRhIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+)}a{background-color:transparent;color:#0051c3;text-decoration:none;transition:color .15s ease}a:hover{color:#ee730a;text-decoration:underline}.main-content{margin:8rem auto;max-width:60rem;width:100%}.heading-favicon{height:2rem;margin-right:.5rem;width:2rem}@media (width <= 720px){.main-content{margin-top:4rem}.heading-favicon{height:1.5rem;width:1.5rem}}.footer,.main-content{padding-left:1.5rem;padding-right:1.5rem}.main-wrapper{align-items:center;display:flex;flex:1;flex-direction:column}.font-red{color:#b20f03}.spacer{margin:2rem 0}.h1{font-size:2.5rem;font-weight:500;line-height:3.75rem}.h2{font-weight:500}.core-msg,.h2{font-size:1.5rem;line-height:2.25rem}.body-text,.core-msg{font-weight:400}.body-text{font-size:1rem;line-height:1.25rem}@media (width <= 720px){.h1{font-size:1.5rem;line-height:1.75rem}.h2{font-size:1.25rem}.core-msg,.h2{line-height:1.5rem}.core-msg{font-size:1rem}}#challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI2ZjNTc0YSIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjZmM1NzRhIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+);padding-left:34px}#challenge-error-text,#challenge-success-text{background-repeat:no-repeat;background-size:contain}#challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=);padding-left:42px}.text-center{text-align:center}.pow-button{background-color:#0051c3;border:.063rem solid #0051c3;border-radius:.313rem;color:#fff;font-size:.875rem;line-height:1.313rem;margin:2rem 0;padding:.375rem 1rem;transition-duration:.2s;transition-property:background-color,border-color,color;transition-timing-function:ease}.pow-button:hover{background-color:#003681;border-color:#003681;color:#fff;cursor:pointer}.footer{font-size:.75rem;line-height:1.125rem;margin:0 auto;max-width:60rem;width:100%}.footer-inner{border-top:1px solid #d9d9d9;padding-bottom:1rem;padding-top:1rem}.clearfix:after{clear:both;content:"";display:table}.clearfix .column{float:left;padding-right:1.5rem;width:50%}.diagnostic-wrapper{margin-bottom:.5rem}.footer .ray-id{text-align:center}.footer .ray-id code{font-family:monaco,courier,monospace}.core-msg,.zone-name-title{overflow-wrap:break-word}@media (width <= 720px){.diagnostic-wrapper{display:flex;flex-wrap:wrap;justify-content:center}.clearfix:after{clear:none;content:none;display:initial;text-align:center}.column{padding-bottom:2rem}.clearfix .column{float:none;padding:0;width:auto;word-break:keep-all}.zone-name-title{margin-bottom:1rem}}.loading-spinner{height:76.391px}.lds-ring{display:inline-block;position:relative}.lds-ring,.lds-ring div{height:1.875rem;width:1.875rem}.lds-ring div{animation:lds-ring 1.2s cubic-bezier(.5,0,.5,1) infinite;border:.3rem solid transparent;border-radius:50%;border-top-color:#313131;box-sizing:border-box;display:block;position:absolute}.lds-ring div:first-child{animation-delay:-.45s}.lds-ring div:nth-child(2){animation-delay:-.3s}.lds-ring div:nth-child(3){animation-delay:-.15s}@keyframes lds-ring{0%{transform:rotate(0)}to{transform:rotate(1turn)}}@media screen and (-ms-high-contrast:active),screen and (-ms-high-contrast:none){.main-wrapper,body{display:block}}.rtl .heading-favicon{margin-left:.5rem;margin-right:0}.rtl #challenge-success-text{background-position:100%;padding-left:0;padding-right:42px}.rtl #challenge-error-text{background-position:100%;padding-left:0;padding-right:34px}</style><meta http-equiv="refresh" content="390"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div id="challenge-error-title"><div class="h2"><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '3',cZone: "www.crunchyroll.com",cType: 'interactive',cNounce: '13717',cRay: '8b4724494d7d7d13',cHash: '74aac384b163ea7',cUPMDTk: "\/simulcastcalendar?filter=premium&date=2024-08-12&__cf_chl_tk=4GBsVwiVGB0gwQgiBQxNpyuy_LPpc2tX5XHjSXHbK7w-1723871259-0.0.1.1-4095",cFPWv: 'g',cTTimeMs: '1000',cMTimeMs: '390000',cTplV: 5,cTplB: 'cf',cK: "",fa: "\/simulcastcalendar?filter=premium&date=2024-08-12&__cf_chl_f_tk=4GBsVwiVGB0gwQgiBQxNpyuy_LPpc2tX5XHjSXHbK7w-1723871259-0.0.1.1-4095",md: "s7Yi_Fm0mFx8HFhrp.D5OAsEJ7BNFjk0jn7WTYCAztU-1723871259-1.1.1.1-vHSxjNLxbNZsPaQjSq6_Al4lCqu.MVPAR8Xz7CFcZzUBMfhXQlCu3M0CGjBY0yhon8Z5mzOHid9GEZhxUd.Y.5HRGDnkPR9MMEI_FLsbOW8JN5_PUvoqoXjLHZ4jVbIUU6BOB9RhqoV7bg9Gue34K.2hXjEndHvY7geVqZq0WRvJ0nGua08GGg3vXFGWe5YnvzPJV8U0Wo1hnpOi3XmqEQecg.f3nRTdgoYCXGB5POHbLnhXWfdouqWEBbrAktnmT5Pf.ZOaLIzCS.9nUhMvABChiLUH9RPsFR4R8_vOxwRYTNSWkujaiQCyk8SFHbrDdtX4jn_o1KW3k.GKhF1Le1PiGQ1WVXF0SfouVBL0A0nsCHzSLDmQdKv64OKgBw4DaByEnL33zk4l4BEUEN0rg63bdoF44jvITfBH2F4MnlVNHdphDC2tTrpsXmQbiUJKz18xKU2qZjG7iX5nyf14HiMx75ZPtPrjbxUiSxEOHlztgkV1wL.qdAykDIHcwITnFrIGS_XfFISwe1Jpcp_GziU9UDno0hH2lTH0_3YhsrkixQhTYuhVboAsTAMTB2JIjzfYmS2MPO.VsgFATwBozKKvX.3Hx_RvPoDlv7j6PHBr1hqZdNU0KYKXYlujwA4YN8_dp82AFaMpUEORXF3krkZ6K0rk2poEIyZmKnmGikQpmEGairNl57sfv_wpZNTjt9sNtmKOZL7qVe4EXprUSy5YjdCexJSHHqkFdtQcHd2omXRdsR9ieArSpkbTiLjCRSoLWdGhk0hoLt4nw9NC7mFgWHxHIFgKMkDjEE4Eg2MvpiI1pp2Lq_7kVOy3jP7BaTY5fA9L3TOm811edUdkaKHQKFCQODGI07_rSkWe6Stgde2xM.wCuNyl_m9duiPqXZUVVLPDkHN2Vg3axSxoTIzeXfAk3Q77BhXa.O4SWvFPc1UTOyFzJQslp_s3hRBO1uXluZRwJyDvAVuMNxPxb73JZ1rad8SxEZxJfmR5P99ut66B1Xm4aaSA8FwTCMX9jsy0Dey2t3st1bJV8YUIQmPPUYfcsqkcQ13dDmo7XHaGFfM41ZrRBp_TJg7BokW_SUYtMhsVgEUFHK8M_SgHF7r9cyiQBgJOHi6ri3xyfx8QxyPx8aZdS_3vmz9dNp.ue2ZNPEoW0RRFknURfKZQONoxysQPC2W0GANFW7N1O6mWBWw5jGOHiW7i3PTXpqRLPnSndwtmhTDFx9Nu1GxvbUpvTIuzEvCBKT8cGJIWBysZYUm1dDoz1g_ZYveni4pVgWFjkA.uEkhh9MtlFNFSD4C0Bo8P9XQ.G2qkhjYPBji90_9aE3TiET8uuWQw4CCp_DgIt2yfeVn._8e._Y93mNjHOVGFj0iXZEnyD_kQRfLLnHaCB_DqbDCYWqHeB4dsszsFWTStVEQMA_BySPHBKoAs.zbnEt7SQlo_lpGkBuL4957hK_28xwozhYGWIxvQuUOa9JjV4mGMMpWV.76SG8bi44LjgqEP.vwYMAaDwTWVSoyG5L8biDfq6Df3ptmgyvvjUOmmNdWoOX87UoGNjAFFJv07zxcoyr7QDQqgMBECOg1WsRYmop6tjO7E5oZ6GkGFOMncxkmj4iC7alHAWhhwUKEIsobuNKqrNxCn6og",mdrd: "dwFRpQ0KcIgex7_j5iwGbBq4SJRowILo5R2Wsh2dhQo-1723871259-1.1.1.1-Gxa3BVDu9sR.B2BkAXfEn4yVGaIe1K0WBggUVAgGo_PQv1P_dCquPsS202T2MBF7iGCY7JkcZnFoTYZwg7Kc6tFpxhAlBoE_tobBU5s3w1ecHCEKf.a6q9L8qNO9jgHfV9tQZ4JNX2YHbnJUZxFThmOtYM_YPh81OpmVAUmJfEecRPJnd4nYTJu.C7kfnhT4wsQzSh8TKfPE24OI0eqd8kgIEQU7Fvw3GB03RKeCuz7F5HISEdyQLpmLT7HFa_EbElf5lq.yc9AQg0DzJuY2Mn5enpT4EgCtblF_W2Ax68yVoTrxWIm6vtyrJNTfxyLDHz7h18KRy838c0yqDG.7pCfAfJmHkXj.A2dxDZJZvYjAtG5Sq.v0srGXUvlkOAlVvvH.PQkTmSnfCCdwoeDpjk_4_lpAkLR6kxaKHb8JQtYWGwsi8koZ77aoUVQIgZeu9F7xzZMKX.RjBHvjgIPFQoNylIL4B2qHilvuF9D.8CslFjT66rCsoulFWZn3hix21utLfTRX4Y8s96oE4TFJggUYUZTiErGMtlKxai_Gx5laIpU5GelBf1LXU0CkzertqOZLxTWTKCshmSQBKTkDDDqXqkhvkDad_SJ5bdNWnuU5k9YLyPOShz3Vl6JtDvaeth.3c98xqwyELWzOeVPxdeUiOm_aCJzg1.qc6xi0Z.NW0fjmBHrJ6pQ.iZpkEEXygf.pnt3h0HEIUnFZtfWaUNKexFIEjf01oRtSza1MeYbgNANycG81G7J5Gqnsnliw0KjWdYtPKvrdeVB7sOtyA67qKaNitT2ytamaVMZt1e2EAJTBntRovLgGt9UiEgbcYgHYWyCgFi2GedK_yyY73XPs6PoEM70bX8sKY5QT2UR6WlfmfsGkbnFUpG2bATYUSaOlz5j9OKBRIqzNz0s_Oc0PUatAEFxSxlyIoXQQMsPxtTZ2zGgX4kTq.Lvbfd0pVKx4UO6h806W9ZTi_.cj..X1W2C8oE6ed5XEESxnTsVOutGpDKgoBzoXr9ZiED1hK1iyzcr2NDRqFfJzsmvLYtil0aQ0GxZdyXIcdpZvYVBbNBdvUpQRxqldR5okUwpHwN7FA2lB0gbaurpUYHnzNOVtJ4GOXiXKcTnJfZwx0dr1coPP8OytICtLxOodFoQ6kQfNHIX5UHCKonpyJhqdxCAWN.dUPJ_TCxYglf1.ayWYD5Db3Hr4fKoYVgscJXyenolrf9ixw_ELUaQS57DCPpsgYokMjT_2pde_VzTJZBlFBxgoyZZ12ARd.1GUTb_NcOzIKCNbjS9_LFbzzxh1OXmirBcn4_nBICsxIcShJANqeyVnuS6LsdoXcE2AVlEo6IN.ta9AWhlR_j.vw7utnlY24lHCUk30ANkT.XUTNGA_xoiOjaAl8ME525n3L3avN...E0EoEvxzcQihu9ZSp751Q_bcguuAxoe5hSedQNWGzTWzRkxIi0j6kk.1AWPiyqfHQeEWGhTL6MuHV9qnsXTWklZ8dgYQBM4ZRMvIPP6wqz_oAvoc5H5TGJgdX6CipPeiqUsu9iF6bmrCPjlO9vFEKzbXaEqkrzWKKGELUl7k4A8aC9BnkGCx_JG4POUpNZqRQx5MSXFjRxZ_yI1Da2MUBQWwGh.uXT80zQNivVagNmH4SGA9Lhahqpm8Mh3HCgOqSh4LHJEldzoAZu2LgUrELVCyMgB9osj8yr7Q6vJDp3.22JUOrgetbwsos8oHzk8x9gMm5HklQcB70CB1aAdXoSttp9vUSgNG51sj_hg8M.AdUXf6dWQ0.iekmKo1Tby5UHfPr9MmO3bNgdktq9EqCZmxB1VHkbMTZ2NHdiOAvyCirj8LuK0gRnW0bFmL83fBtqm3eVuG52iIz34Rztl80SiJmodjZIvsWy.yML7ZEE.6kBSAl4Y0jmvKrXhFoD988FbzTK7mHHjjhlFPB6I68aziFDjYkZYTGkipmV9lXLvrQaisxW9jr3b1x35zMu1g13sq7bQIdMbkhEWbT75CptXiLLu6yyqm.7_c2xCUSJaM1R2b2zSFL7lWqxBJk27MQNp9OAoGG1zWijuQqrGiToO81tVrZKNfaFZ9SpQ4cPV6BH6XYLGvaLzqAun68FZb7DRB7nOW1R6PlXQxZvZTTV8vfR7jWTuH8kI6j8pjGt1K3gJq7QXUTOgkURyFf5PBZTaBcEB0vQJpjkooGcvsQ5j0C7ic39fqIAsNelI2DgW.p01TlGSNHd.Rg2hxLZPhhWJIkvZI5H8IG6gBsiyMSREW35Ds_GMbGAAX95Zu8OUCRZX_AxHtG6DxQz9FAE6ckgU99LNNUF5eudRBqA",cRq: {ru: 'aHR0cHM6Ly93d3cuY3J1bmNoeXJvbGwuY29tL3NpbXVsY2FzdGNhbGVuZGFyP2ZpbHRlcj1wcmVtaXVtJmRhdGU9MjAyNC0wOC0xMg==',ra: 'Q3J1bmNoeXJvbGwvMS45LjAgTmludGVuZG8gU3dpdGNoLzE4LjEuMC4wIFVFNC80LjI3',d: 'bRAZTYEeg8+yT85gS2Pz3a/00tdkDEhXXAXVtpmXFY4Wkb2HCPCWWMiSSHpCcLZAA/r9f3cBSK23/nCWWF01gKt5Jb40ln6sF5/L2KB8ixN+rZmmYBJr1yZQ7vsa+GupwlfbJSj40BbAQMNqWUVGYjvwvfzVG045TdJIkH+joL4f2v4xwbWUgixRh0MuWm0V5C0iE+u4ApTUtX60INHGvBAE76ir3wlvqX3lG56jw4tBFTzrOJJ8JZxvLNak+UVhcmhrNjtG/dXUG+aWO6MhSX2Bn4UQsSeY+S2JfXmkgtIAPFmrYT/30iFcydEYdz6Dr2YwKAfn4JpI/QbW2lNcTzEkKPCYnanwIjYYVj+Pv7Ph6C49blzMwx/NSqWvOwcNZGGGfup6y+1wWd7aZKBo3UmAL5ng6o3HE9VJpUsGfBh6c6RMgkBsmCnr0TvSUMq70E+KD1Bj3+raXNXqauv/BxXpjX3dCJFI5J+CK9/1HYg9Unep2ir5p6OsYGwt1rtFC2kXhksPyK0felzGSZsQ2lJBfhAMj0+/ltEV89em3Ds=',t: 'MTcyMzg3MTI1OS4wMDAwMDA=',cT: Math.floor(Date.now() / 1000),m: '45S9Ww9HOPZiSSXreOo4uixkdKjyJDCJXN7wu+gol0I=',i1: '6eoaM6mVzU/qlT/FLUqrpg==',i2: 'kTsO7X7JACBWyemwWDx5TA==',zh: 'qQz4tblgEgtOKuLwUaA7NrEUXyzFHvjAH4jkpQCn35I=',uh: 'DDRZRZ97EVghWigYGAv0UXDD0lpoS+/00QGzSz7Hf44=',hh: 'X/ui56Hpfhv5vN0FUDU58Tk8kOdH4hwp+B7yjRL1zVA=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1?ray=8b4724494d7d7d13';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/simulcastcalendar?filter=premium&date=2024-08-12&__cf_chl_rt_tk=4GBsVwiVGB0gwQgiBQxNpyuy_LPpc2tX5XHjSXHbK7w-1723871259-0.0.1.1-4095" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>
No days found in the HTML document.

**Comment by rifatozkancomtr** [comment]
![image](https://github.com/user-attachments/assets/ed09df8d-860b-4ad1-9897-e0ee062e6f1d)

It got fixed when I changed the stream endpoint to chrome.

**Comment by Elwador** [comment]
that has no impact on the calendar - you can also just use the custom calendar that is more reliable
