### ISSUE TITLE
[Bug] Problem with programme window resolution

### ISSUE THREAD

**Issue by Vorffeed** [Crunchy-DL/Crunchy-Downloader#89]
I don't know what happens now that every time I initialise the program the window has a different resolution than when I closed it and before this didn't happen.

And I have to adjust it all the time, because sometimes it opens to fill the whole screen.

Could you implement an option to tell it the width and height?
I mean, first a button that allows you to see the values of the window (width/height) and you can see the value you want to have when adjusting the window and under that button you can put those values to leave fixed that resolution of the window.

**Comment by Vorffeed** [comment]
I have just created the thread for the same reason, because I read that you had done that because someone asked for it and I am in the last version of the programme and it doesn't do it, I have closed and opened the programme about 10 times before creating the thread in case it was my imagination because I was seeing that I had to change the resolution of the window all the time, but it doesn't do it, the resolution varies all the time and it is not the same as the one I close the window with.

![image](https://github.com/user-attachments/assets/6efe6622-a052-4c82-a9e8-0509274fceb8)

![image](https://github.com/user-attachments/assets/048ba4c6-72a8-409f-8153-b15b1252cbe2)

Just so you can see, I just opened and closed it now, and it changed the window size again ><
That's why I was telling you an option to set the window manually.

**Comment by Elwador** [comment]
try it now with the new release - [v1.5.21](https://github.com/Crunchy-DL/Crunchy-Downloader/releases/tag/v1.5.21)

**Comment by Vorffeed** [comment]
Perfect, I have opened and closed it a couple of times and the resolution of the window is maintained. 👍
