### ISSUE TITLE
v1.4.19 App crashed and close after login in

### ISSUE THREAD

**Issue by davidpoh83** [Crunchy-DL/Crunchy-Downloader#9]
Hello, firstly, thanks for the great effort in bring this tool available to us. Thank you.

I have recently updated the app to version 1.4.19, upon entering the credentials in the login screen and hit login, the app crashed and exited. When I try to re-launch the app, the app open up and when I click on the user login icon, the app immediately close without any errors.

I have tried to enable the logging, and did the same steps and the app crashed. But there is no log being written in the logfile.txt.

**Comment by Elwador** [comment]
so the login worked with an earlier version for you?

**Comment by davidpoh83** [comment]
Yes, the earlier version v1.4.15 works fine for me. I'm using Windows 10 Pro 22H2 with updated .Net Desktop Framework.

**Comment by Elwador** [comment]
fixed in the new version - also everything else should have worked fine you just couldn't go to the account page

**Comment by davidpoh83** [comment]
Hi Elwador, appreciate your prompt response in regards to this issue. I downloaded the latest v1.4.20 and was able to login successfully. However, it says that I do not have a valid subscription instead and trying to add the video to download list says that I do not have an active subscription error. However, I confirm that my account is still active and I am able to stream videos from the official websites successfully. It didn't work as per the v1.4.15 previously.
![Capture](https://github.com/Crunchy-DL/Crunchy-Downloader/assets/24598145/cd793346-0f0d-4003-9228-c54cfe97d4c5)

**Comment by Elwador** [comment]
yes i have included a check for the subscription status

if you don't mind asking what kind of subscription do you have? 

i tested with an account without a subscription, one with a expired trial and one with a running subscription - i thought it would be reliable

**Comment by davidpoh83** [comment]
I'm subscribed as a mega fan member as per screenshot.

![image](https://github.com/Crunchy-DL/Crunchy-Downloader/assets/24598145/86d065f2-ce96-4e0c-8612-4bb95396bf14)

**Comment by davidpoh83** [comment]
It works great! I can login successful now and the status is showing subscription refreshing in some hours. Thanks Elwador, everything works great now. Thank you!
