### ISSUE TITLE
[Bug] Problem with temporary folder option in the configuration

### ISSUE THREAD

**Issue by Vorffeed** [Crunchy-DL/Crunchy-Downloader#90]
I have noticed that there are two problems with this new function.
1º if you use this option it doesn't delete the folders generated with the code of the episode and all the folders generated for each downloaded episode remain in this temporary folder but without any content inside.
2nd I do not know if it happens with the audio or video if you only want to download one, the case is that I went to download a few episodes at once and two episodes did not bring the Spanish subtitle and I had to disable the audio and video from settings to not download it again and put that only download the subtitle the es-419 and what was my surprise that has been inside the temporary folder, inside the folder with the number of the episode and it has not moved it to the download folder of the series, as it used to happen before when this option was not implemented.

**Comment by Elwador** [comment]
> 1º if you use this option it doesn't delete the folders generated with the code of the episode and all the folders generated for each downloaded episode remain in this temporary folder but without any content inside.

it does delete the folders but only if you close the downloader
