### ISSUE TITLE
[Bug] los episodios no quedan con un subtitulo predeterminado

### ISSUE THREAD

**Issue by BattouKen** [Crunchy-DL/Crunchy-Downloader#91]
normalmente siempre el downloader dejaba como sub predeterminado el primer softsub que uno elegía y en esta ultima version ya no lo hace.

![image](https://github.com/user-attachments/assets/692f884d-5d04-47f3-a088-73b63046fbff)

![image](https://github.com/user-attachments/assets/2b158b27-ac9b-403a-88fa-dd223572ad81)

**Comment by Elwador** [comment]
not sure what you are trying to say but it sets the dub/sub to default that is set in the settings and that still works as expected

**Comment by Elwador** [comment]
since you didn't reply i will close this
