### ISSUE TITLE
[Bug] Duplicate episodes appearing in History

### ISSUE THREAD

**Issue by petenun** [Crunchy-DL/Crunchy-Downloader#93]
I noticed that some series are displaying a second "(English Dub)" season even though the original was working just fine. This results in duplicate episodes being downloaded. 

![image](https://github.com/user-attachments/assets/af781052-afde-4b2d-adba-1fcb2d880af7)

**Comment by Elwador** [comment]
there was a bug a few versions ago where it was possible that these dub season get added - i think they shouldn't be added in the current version 

for that case there is the edit button with which you can delete the dub season

**Comment by Elwador** [comment]
should be fixed now

**Comment by petenun** [comment]
Thanks for updating that. I'll give it a test with tomorrow's downloads.

**Comment by Elwador** [comment]
you still have to remove the duplicate season
