### ISSUE TITLE
[Feature] Is there any way to update current crd.exe without downloading from github?

### ISSUE THREAD

**Issue by R4H4T069** [Crunchy-DL/Crunchy-Downloader#98]
Before you open a new issue, please make sure you have done the following:**

1. **Search Closed Issues**
   - Have you checked the closed issues to see if your Feature request has already been addressed
   - [Search Closed Issues](https://github.com/Crunchy-DL/Crunchy-Downloader/issues?q=is%3Aissue+is%3Aclosed)

2. **Check the Wiki and Discussions**
   - The [Wiki](https://github.com/Crunchy-DL/Crunchy-Downloader/wiki).
   - The [Discussions](https://github.com/Crunchy-DL/Crunchy-Downloader/discussions) section is a great place to see if others have encountered and solved similar issues.

**Comment by Elwador** [comment]
https://github.com/Crunchy-DL/Crunchy-Downloader/discussions/79
