### ISSUE TITLE
[Feature] download different dub in one click

### ISSUE THREAD

**Issue by xshion13** [Crunchy-DL/Crunchy-Downloader#99]
My idea is that while the initial configuration I set is for Japanese audio with Spanish subtitles, the episode later appears in Spanish-dubbed audio. However, when I try to download it, I still get the version with Japanese audio and Spanish subtitles. I would like to download the version without subtitles in Spanish-dubbed audio without having to change the program settings every time I want to do this. Additionally, I would like to concatenate the language into the filename. For example, instead of just 'Quality Assurance in Another World - S01E08 [480p],' I would like it to be 'Quality Assurance in Another World - S01E08 [480p] [JA-JP]' or '[ES-MX],' etc.
![image](https://github.com/user-attachments/assets/2218249f-bcf5-40fa-92ec-07c9c343d6f9)

**Comment by okaneyo** [comment]
Nice idea. I'd like to see an option to download multiple audio tracks, say: Japanese and English etc (if available)

**Comment by TaMaGo-TTV** [comment]
Just set Spanish as a default DUB with Jap? Or am I misunderstanding something?

**Comment by xshion13** [comment]
still can't download, it always says "hardsub not available", what's the correct configuration to download jap+subs and spanish dubs at the same time without changing settings? filename changed but still need change settings like 3 weeks ago 
![image](https://github.com/user-attachments/assets/f8a5384a-283f-4447-b463-13803441a5da)

![image](https://github.com/user-attachments/assets/3346af28-a382-4a09-a309-75a4d9150d8a)

**Comment by Elwador** [comment]
download the downloader a second time setup the settings how you like and you don't have to change anything if you want to switch between your 2 configurations

**Comment by xshion13** [comment]
still can't hardsubs is mandatory i always download as mp4 and softsubs not working in mp4 format
